# Bibliography {.unnumbered}

"100 Best-Selling Art History Books of All Time." Book Authority.\
https://bookauthority.org/books/best-selling-art-history-books.   

Bolin, Paul E. "Discussions and Depictions of Women in H. W. Janson's History of Art, Fourth Edition." *Journal of Social Theory in Art Education* 15 (1996): 146-159, VCU Scholars Compass.

Boston University Arts & Sciences: Archaeology. "Fred S. Kleiner: Professor Emeritus of History of Art and Architecture and Archaeology." Accessed April 7, 2022. https://www.bu.edu/archaeology/profile/kleiner/.

Croix, Horst de la, and Richard G. Tansey. *Gardner's Art Through the Ages.* Eighth Edition. San Diego: Harcourt Brace Jovanovich, 1986.

Croix, Horst de la, Richard G. Tansey and Diane Kirkpatrick. *Gardner's Art Through the Ages.* Ninth Edition.San Diego: Harcourt Brace Jovanovich, 1991.

Davies, Penelope J.E., Walter B. Denny, Frima Fox Hofrichter, Joseph F. Jacobs, Ann S. Roberts, David L. Simon. *Janson's History of Art.* Seventh Edition. New Jersey: Pearson Prentice Hall, 2007.

Davies, Penelope J.E., Walter B. Denny, Frima Fox Hofrichter, Joseph F. Jacobs, Ann S. Roberts, David L. Simon. *Janson's History of Art*. Eighth Edition. New Jersey: Pearson Prentice Hall, 2011.

Gardner, Helen. *Art Through the Ages; An Introduction to Its History and Significance.* First Edition. New York: Brace, Harcourt, 1926.

Gardner, Helen. *Art Through the Ages; An Introduction to Its History and Significance.* Second Edition. New York: Brace, Harcourt, 1936.

Gardner, Helen. *Art Through the Ages.* Third Edition. New York: Brace, Harcourt, 1948.

Gardner, Helen. Revised by Horst de la Croix and Richard G. Tansey. *Gardner's Art Through the Ages.* Fifth Edition. New York: Harcourt, Brace, 1970.

Gardner, Helen. Revised by Horst de la Croix and Richard G. Tansey. *Gardner's Art Through the Ages.* Seventh Edition. New York: Harcourt Brace Jovanovich, 1980.

Gardner, Helen. Revised by Horst de la Croix and Richard G. Tansey. *Gardner's Art Through the Ages.* Sixth Edition. New York: Harcourt Brace Jovanovich, 1975.

Gardner, Helen. Revised by Sumner M. Crosby and the Dept. of the History of Art, Yale University. *Art Through the Ages.* Fourth Edition. New York: Harcourt, Brace, 1959.

Hérubel, Jean-Pierre V.M., Benjamin R. Sloan, and Matthew N. Hannah. "Evolution of a Canonical Art History Textbook: Charting Bibliographic Elements in *Gardner's Art through the Ages."* *Art Documentation: Journal of the Art Libraries Society of North America* 39, no. 1 (2020): 12-23, The University of Chicago Press Journals.

Hills, Patricia. "Art History Textbooks: The Hidden Persuaders." *Artforum* 14 (Summer 1976): 58-61, ProQuest.

Ingalls, Zoë. "A Son Revises His Father's Classic Art-History Textbook." *The Chronicle of Higher Education,* August 11, 1995. https://www.chronicle.com/article/a-son-revises-his-fathers-classic-art-history-textbook/.

Jaffee, Barbara. "9. 'Gardner' Variety Formalism: Helen Gardner and Art through the Ages." In *Partisan Canons* edited by Anna Brzyski, 203-224. New York: Duke University Press, 2007. https://doi.org/10.1515/9780822390374-010.

Janson, Anthony. "Interview with Anthony F. Janson, March 15/19, 2007." Interview by Sherman Hayes. *University of North Carolina Wilmington Archives and Special Collections*. March 15-19, 2007. 

Janson, H. W., and Anthony F. Janson. *History of Art.* Third Edition. New York: Harry N. Abrams, 1986.

\
Janson, H. W., and Anthony F. Janson. *History of Art.* Fourth Edition. New York: Harry N. Abrams, 1991.

Janson, H. W., and Anthony F. Janson. *History of Art.* Fifth Edition. New York: Harry N. Abrams. New Jersey: Prentice Hall, 1995. 

Janson, H. W., and Anthony F. Janson. *History of Art.* Sixth Edition. Harry N. Abrams. New York: Prentice Hall, 2001.

Janson, H. W., and Dora Jane Janson. *History of Art: A Survey of the Major Visual Arts from the Dawn of History to the Present Day.* First Edition, Second Printing. New York: Harry N. Abrams, 1963. 

Janson, H. W., and Dora Jane Janson. *History of Art: A Survey of the Major\
Visual Arts from the Dawn of History to the Present Day.* First Edition Revised and\
Enlarged. New Jersey: Prentice-Hall, 1969.

Janson, H. W., and Dora Jane Janson. *History of Art: A Survey of the Major Visual Arts from the Dawn of History to the Present Day.* Second Edition. New York: Harry N. Abrams, 1977. 

Kader, Themina. "The Bible of Art History: Gardner's Art through the Ages." *Studies in Art Education* 41, no. 2 (Winter, 2000): 164-177,

Kennedy, Randy. "Revising Art History's Big Book: Who's In and Who Comes Out?" *New York Times,* March 7, 2006. https://www.nytimes.com/2006/03/07/arts/design/revising-art-historys-big-book-whos-in-and-who-comes-out.html.

Kleiner, Fred S., Christin J. Mamiya and Richard G. Tansey. *Gardner's Art Through the Ages.* Eleventh Edition. Fort Worth: Harcourt College Publishers, 2001.

Kleiner, Fred S. and Christin J. Mamiya. *Gardner's Art Through the Ages.* Twelfth Edition. Belmont, CA: Thomson/Wadsworth, 2005.

Kleiner, Fred S. *Gardner's Art Through the Ages: A Global History.* Fifteenth Edition. Boston: Cengage Learning, 2016.

Kleiner, Fred S. *Gardner's Art Through the Ages: A Global History.* Fourteenth Edition. Australia/United States: Wadsworth, Cengage Learning, 2013.

Kleiner, Fred S. *Gardner's Art Through the Ages: A Global History.* Sixteenth Edition. Boston: Cengage Learning, 2020.

Kleiner, Fred S. *Gardner's Art Through the Ages: A Global History.* Thirteenth Edition. Boston: Thomson/Wadsworth, 2009.

Peers, Alexandra. "Canon Fodder." *ARTnews.com*, February 1, 2006.\
https://www.artnews.com/art-news/news/canon-fodder-135/. 

Russell, John. "Prof. H. W. Janson is Dead at 68; Wrote Best-Selling 'History of Art.'" *New York Times,* October 3, 1982. https://www.nytimes.com/1982/10/03/nyregion/prof-h-w-\
Janson-is-dead-at-68-wrote-best-selling-history-of-art.html.

Sears, Elizabeth and Charlotte Schoell-Glass. "An Émigré Art Historian and American: H. W. Janson." *The Art Bulletin*, 95 (June 2013): 219-242. https://doi.org/10.1080/00043079.2013.10786070.

S.J.S.U Scholar Works. "Tansey, Richard G. (1919-1998)." Emeritus and Retired Faculty Biographies. Last modified October 24, 2019. https://scholarworks.sjsu.edu/erfa_bios/240/.

Sorensen, Lee, ed. "Janson, Dora Jane." Dictionary of Art Historians. Accessed April 7, 2022, https://arthistorians.info/jansond.

Sorensen, Lee, ed. "Janson, Horst, Woldemar." Dictionary of Art Historians. Accessed April 7, 2022, https://arthistorians.info/jansonh.

Sorensen, Lee, ed. "Crosby, Sumner McKnight." Dictionary of Art Historians. Accessed April 7, 2022. https://arthistorians.info/crosbys.

Sorensen, Lee, ed. "Gardner, Helen." Dictionary of Art Historians. Accessed April 7, 2022. https://arthistorians.info/gardnerh.

Staff Report, Mercury News. "H. de la Croix, SJS Professor of Art History." *San Jose Mercury News (CA),* March 5, 1992: 3B. NewsBank: America's News -- Historical and Current.

Tansey, Richard G. and Fred S. Kleiner. *Gardner's Art Through the Ages.* Tenth Edition. Fort Worth: Harcourt Brace, 1996.

United States Census Bureau. "U.S. Census Bureau Definitions of Race and Ethnicity." Last modified July 2014. https://www.mobap.edu/wp-content/uploads/2013/01/US-Census-Bureau-Definitions-of-Race-and-Ethnicity.pdf.

University of Michigan. "Memoir: Diane M. Kirkpatrick." Faculty History Project. Accessed April 7, 2022. http://faculty-history.dc.umich.edu/faculty/diane-m-kirkpatrick/memoir.

University of Nebraska-Lincoln. "Christin Mamiya: Emeritus Faculty 2019." Accessed April 7, 2022. https://arts.unl.edu/art/faculty/christin-mamiya.

Weidman, Jeffrey. "Many Are Culled but Few Are Chosen: Janson's History of Art, Its Reception, Emulators, Legacy, and Current Demise." *Journal of Scholarly Publishing,* 38, no. 2 (January 2007): 85-107, http://dx.doi.org/10.3138/0757-4748-121X-17J1.
