# Acknowledgements

Firstly, I would love to thank my parents and my siblings for always encouraging me and supporting me through my undergraduate honors thesis. From helping me navigate daily stress to typing heights and lengths into spreadsheets, they have been the backbone to this process. Additionally, I would love to thank every advisor of mine that I have had through this process. From Prof. Annabel Wharton steering me initially in the right direction of how to start a thesis, to Prof. Hans J. van Miegroet for taking a chance on me, spending time to explain countless topics to me, and helping me discover and understand my academic purpose and in particular, my research questions for my thesis, to Fiene Leunissen who first opened the door for me to data cleaning and analysis, to Prof. Anne-Sophie Radermecker for helping me first understand how to organize data and the idea behind statistical models as well as inspire me to work within the intersection of art history, statistics, and economics, to Prof. Mine Çetinkaya-Rundel for teaching me how to run regression models, and to Prof. Sheila Dillon to creating space for me to work through the process of creating a thesis. Moreover, I want to highlight classmates of mine that have made this experience worthwhile. To Dani Yan and David Smoot who worked through this research with me for the Spring semester of 2021 in Prof. van Miegroet's graduate course, Arts and Markets, to Daniella Paretti who week in and week out has listened to my ideas and limitations and provided incredible feedback along the way, and to Abby Schelinger who has created space for me to ask questions and learn how to create a thesis. Last but most certainly not least, I would like to thank my classmate and tutor, Callie Smith for helping me with model selection and understanding how to understand slope interpretations and model assumptions. The process of creating this work has been incredible.

#  {.unnumbered}
