# Abstract {.unnumbered}

My project surveys the development of *Janson's History of Art* across its eight editions as well as *Gardner's Art Through the Ages* through its sixteen editions, looking particularly at the change in artist demographic through time. Additionally, this paper investigates which external variables such as artist gender, race, ethnicity, nationality, number of exhibitions at the Museum of Modern Art, and number of exhibitions at The Whitney if any, help to infer the magnitude of an artist's inclusion in art history survey texts. I conduct data analysis to assess the demographic representation of artists through editions of *Janson's History of Art* and *Gardner's Art Through the Ages*, a proxy for the art history survey. I compare artist demographics through editions of Janson and Gardner. My findings indicate that coverage of minority artists (defined as non-white and/or from Hispanic or Latino origin and/or female) increases across editions of *Janson's History of Art* and *Gardner's Art Through the Ages*, but remains negligible compared to white male artists not from Hispanic or Latino origin. Moreover, in *Janson's History of Art* through all editions, the percentage of artists who are white is 97.37%, the percentage of artists that are male is 89.99%, and the percentage of artists that are not from Hispanic or Latino origin is 95.82%. In *Gardner's Art Through the Ages*, through all editions, the percentage of artists who are white is 90.02%, the percentage of artists that are male is 85.69%, and the percentage of artists that are not from Hispanic or Latino origin is 91.51%. Both texts display a narrative of the history of art as being predominantly white, male, non-Hispanic or Latinx. Regarding nationality, in Janson, 78.51% of the artists are American, British, French, German, and Spanish, which is very similar to Gardner's 76.58% of those five same nationalities. I have chosen to run a linear mixed-effects model with a random effect of the artist's name, to infer the magnitude of the space given to a particular artist divided by the area of the page of the given edition (total space ratio per page), in *Janson's History of Art* and *Gardner's Art Through the Ages,* using the potential predictor variables: artist gender, race, ethnicity, nationality, the count to year of the number of exhibitions an artist has at the MoMA, and the count to year of the number of exhibitions an artist has at The Whitney. The model with the best AIC, and best explains the variance in the total space ratio per page per artist per edition uses artist nationality and the count to year of the number of exhibitions an artist has in the MoMA as well as the interaction between those two variables. With a log transformation applied to the outcome variable as it is heavily right-skewed, my linear mixed-effects model yields a conditional r squared of 53.23%. Such denotes that 53.23% of the variance of total space ratio per page given to an artist in a given edition can be explained by the model.

**JEL Numbers:** C80, Y10, Z11

**Key Words:** Cultural Economics, Art History, Statistics, Historiography, Data Collection Methodology, Linear Mixed-Effects Modeling.
