<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
  <meta charset="utf-8">
  <meta name="generator" content="quarto-0.9.21">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <title>holland-thesis - 1&nbsp; Quantifying Art Historical Narratives</title>
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    span.underline{text-decoration: underline;}
    div.column{display: inline-block; vertical-align: top; width: 50%;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
  </style>

  <script src="../site_libs/quarto-nav/quarto-nav.js"></script>
  <script src="../site_libs/quarto-nav/headroom.min.js"></script>
  <script src="../site_libs/clipboard/clipboard.min.js"></script>
  <meta name="quarto:offset" content="../">
  <script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
  <script src="../site_libs/quarto-search/fuse.min.js"></script>
  <script src="../site_libs/quarto-search/quarto-search.js"></script>
  <link href="../Chapter2/Chapter2.html" rel="next">
  <link href="../index.html" rel="prev">
  <script src="../site_libs/quarto-html/quarto.js"></script>
  <script src="../site_libs/quarto-html/popper.min.js"></script>
  <script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
  <script src="../site_libs/quarto-html/anchor.min.js"></script>
  <link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
  <link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet">
  <script src="../site_libs/bootstrap/bootstrap.min.js"></script>
  <link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
  <link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet">
  <script id="quarto-search-options" type="application/json">{
    "location": "sidebar",
    "copy-button": false,
    "collapse-after": 2,
    "panel-placement": "start",
    "type": "textbox",
    "limit": 20,
    "language": {
      "search-no-results-text": "No results",
      "search-matching-documents-text": "matching documents",
      "search-copy-link-title": "Copy link to search",
      "search-hide-matches-text": "Hide additional matches",
      "search-more-match-text": "more match in this document",
      "search-more-matches-text": "more matches in this document",
      "search-clear-button-title": "Clear",
      "search-detached-cancel-button-title": "Cancel",
      "search-submit-button-title": "Submit"
    }
  }</script>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body class="floating">
<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Quantifying Art Historical Narratives</span></h1>
      <button type="button" class="quarto-btn-toggle btn">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">holland-thesis</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter1/Chapter1.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Quantifying Art Historical Narratives</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Chapter2/Chapter2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Model Exploration</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
<h2 id="toc-title">Table of contents</h2>
<ul>
<li><a href="#abstract" class="nav-link active" data-scroll-target="#abstract"> <span class="header-section-number">1.1</span> Abstract</a></li>
<li><a href="#introduction-and-context" class="nav-link" data-scroll-target="#introduction-and-context"> <span class="header-section-number">2</span> Introduction and Context</a>
<ul class="collapse">
<li><a href="#inspiration-for-research" class="nav-link" data-scroll-target="#inspiration-for-research"> <span class="header-section-number">2.1</span> Inspiration for Research:</a></li>
<li><a href="#why-gardners-art-through-the-ages" class="nav-link" data-scroll-target="#why-gardners-art-through-the-ages"> <span class="header-section-number">2.2</span> Why <em>Gardner’s Art Through the Ages:</em></a>
<ul class="collapse">
<li><a href="#discourse-of-authorship" class="nav-link" data-scroll-target="#discourse-of-authorship"> <span class="header-section-number">2.2.1</span> Discourse of Authorship:</a></li>
<li><a href="#literature-review" class="nav-link" data-scroll-target="#literature-review"> <span class="header-section-number">2.2.2</span> Literature Review:</a></li>
</ul></li>
<li><a href="#why-jansons-history-of-art" class="nav-link" data-scroll-target="#why-jansons-history-of-art"> <span class="header-section-number">2.3</span> Why <em>Janson’s History of Art</em>:</a>
<ul class="collapse">
<li><a href="#discourse-of-authorship-through-editions" class="nav-link" data-scroll-target="#discourse-of-authorship-through-editions"> <span class="header-section-number">2.3.1</span> <strong>Discourse of Authorship Through Editions:</strong></a></li>
<li><a href="#literature-review-1" class="nav-link" data-scroll-target="#literature-review-1"> <span class="header-section-number">2.3.2</span> <strong>Literature Review:</strong></a></li>
</ul></li>
</ul></li>
<li><a href="#significance-of-research" class="nav-link" data-scroll-target="#significance-of-research"> <span class="header-section-number">3</span> <strong>Significance of Research:</strong></a></li>
<li><a href="#research-questions" class="nav-link" data-scroll-target="#research-questions"> <span class="header-section-number">4</span> <strong>Research Questions:</strong></a></li>
<li><a href="#methodology" class="nav-link" data-scroll-target="#methodology"> <span class="header-section-number">5</span> <strong>Methodology:</strong></a>
<ul class="collapse">
<li><a href="#data-collection" class="nav-link" data-scroll-target="#data-collection"> <span class="header-section-number">5.1</span> Data Collection:</a>
<ul class="collapse">
<li><a href="#textbooks" class="nav-link" data-scroll-target="#textbooks"> <span class="header-section-number">5.1.1</span> Textbooks:</a></li>
<li><a href="#museum-data" class="nav-link" data-scroll-target="#museum-data"> <span class="header-section-number">5.1.2</span> Museum Data:</a></li>
</ul></li>
<li><a href="#data-preparation" class="nav-link" data-scroll-target="#data-preparation"> <span class="header-section-number">5.2</span> Data Preparation:</a></li>
<li><a href="#model-selection" class="nav-link" data-scroll-target="#model-selection"> <span class="header-section-number">5.3</span> Model Selection:</a>
<ul class="collapse">
<li><a href="#data-preparation-for-modeling-purposes" class="nav-link" data-scroll-target="#data-preparation-for-modeling-purposes"> <span class="header-section-number">5.3.1</span> Data Preparation for Modeling Purposes:</a></li>
<li><a href="#linear-mixed-effects-model" class="nav-link" data-scroll-target="#linear-mixed-effects-model"> <span class="header-section-number">5.3.2</span> Linear Mixed-Effects Model:</a></li>
</ul></li>
</ul></li>
<li><a href="#exploratory-data-analysis-gardners-art-through-the-ages-and-jansons-history-of-art-through-editions" class="nav-link" data-scroll-target="#exploratory-data-analysis-gardners-art-through-the-ages-and-jansons-history-of-art-through-editions"> <span class="header-section-number">6</span> Exploratory Data Analysis: <em>Gardner’s Art Through the Ages</em> and <em>Janson’s History of Art</em> Through Editions</a>
<ul class="collapse">
<li><a href="#count-through-editions" class="nav-link" data-scroll-target="#count-through-editions"> <span class="header-section-number">6.1</span> <strong>Count Through Editions:</strong></a></li>
<li><a href="#gender-through-editions" class="nav-link" data-scroll-target="#gender-through-editions"> <span class="header-section-number">6.2</span> <strong>Gender Through Editions:</strong></a></li>
<li><a href="#race-through-editions" class="nav-link" data-scroll-target="#race-through-editions"> <span class="header-section-number">6.3</span> <strong>Race Through Editions:</strong></a></li>
<li><a href="#ethnicity-through-editions" class="nav-link" data-scroll-target="#ethnicity-through-editions"> <span class="header-section-number">6.4</span> <strong>Ethnicity Through Editions:</strong></a></li>
<li><a href="#nationality-through-editions" class="nav-link" data-scroll-target="#nationality-through-editions"> <span class="header-section-number">6.5</span> <strong>Nationality Through Editions:</strong></a></li>
</ul></li>
<li><a href="#exploratory-data-analysis-jansons-history-of-art-and-gardners-art-through-the-ages-vs.-total-space-ratio-per-page-per-artist-per-edition-space_ratio_per_page_total" class="nav-link" data-scroll-target="#exploratory-data-analysis-jansons-history-of-art-and-gardners-art-through-the-ages-vs.-total-space-ratio-per-page-per-artist-per-edition-space_ratio_per_page_total"> <span class="header-section-number">7</span> Exploratory Data Analysis: <em>Janson’s History of Art</em> and <em>Gardner’s Art Through the Ages vs.</em> Total Space Ratio per Page per Artist per Edition <code>space_ratio_per_page_total</code></a>
<ul class="collapse">
<li><a href="#distribution-of-space_ratio_per_page_total" class="nav-link" data-scroll-target="#distribution-of-space_ratio_per_page_total"> <span class="header-section-number">7.1</span> Distribution of <code>space_ratio_per_page_total</code></a></li>
<li><a href="#space_ratio_per_page_total-vs.-artist_gender" class="nav-link" data-scroll-target="#space_ratio_per_page_total-vs.-artist_gender"> <span class="header-section-number">7.2</span> <code>space_ratio_per_page_total</code> vs.&nbsp;<code>artist_gender</code></a></li>
<li><a href="#space_ratio_per_page_total-vs.-artist_race" class="nav-link" data-scroll-target="#space_ratio_per_page_total-vs.-artist_race"> <span class="header-section-number">7.3</span> <code>space_ratio_per_page_total</code> vs.&nbsp;<code>artist_race</code></a></li>
<li><a href="#space_ratio_per_page_total-vs.-artist_ethnicity" class="nav-link" data-scroll-target="#space_ratio_per_page_total-vs.-artist_ethnicity"> <span class="header-section-number">7.4</span> <code>space_ratio_per_page_total</code> vs.&nbsp;<code>artist_ethnicity</code></a></li>
<li><a href="#space_ratio_per_page_total-vs.-artist_nationality_other" class="nav-link" data-scroll-target="#space_ratio_per_page_total-vs.-artist_nationality_other"> <span class="header-section-number">7.5</span> <code>space_ratio_per_page_total</code> vs.&nbsp;<code>artist_nationality_other</code></a></li>
</ul></li>
<li><a href="#results" class="nav-link" data-scroll-target="#results"> <span class="header-section-number">8</span> Results</a></li>
<li><a href="#discussion" class="nav-link" data-scroll-target="#discussion"> <span class="header-section-number">9</span> Discussion</a></li>
<li><a href="#limitations-and-next-steps" class="nav-link" data-scroll-target="#limitations-and-next-steps"> <span class="header-section-number">10</span> Limitations and Next Steps</a></li>
<li><a href="#appendix" class="nav-link" data-scroll-target="#appendix"> <span class="header-section-number">11</span> Appendix</a>
<ul class="collapse">
<li><a href="#assumptions" class="nav-link" data-scroll-target="#assumptions"> <span class="header-section-number">11.1</span> Assumptions</a>
<ul class="collapse">
<li><a href="#residuals-and-constant-variance" class="nav-link" data-scroll-target="#residuals-and-constant-variance"> <span class="header-section-number">11.1.1</span> Residuals and Constant Variance</a></li>
<li><a href="#normality" class="nav-link" data-scroll-target="#normality"> <span class="header-section-number">11.1.2</span> Normality</a></li>
<li><a href="#linearity" class="nav-link" data-scroll-target="#linearity"> <span class="header-section-number">11.1.3</span> Linearity</a></li>
<li><a href="#independence" class="nav-link" data-scroll-target="#independence"> <span class="header-section-number">11.1.4</span> Independence</a></li>
</ul></li>
<li><a href="#data-dictionary" class="nav-link" data-scroll-target="#data-dictionary"> <span class="header-section-number">11.2</span> Data Dictionary</a></li>
</ul></li>
<li><a href="#bibliography" class="nav-link" data-scroll-target="#bibliography"> <span class="header-section-number">12</span> Bibliography</a></li>
</ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<header id="title-block-header">
<h1 class="title d-none d-lg-block display-7"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Quantifying Art Historical Narratives</span></h1>
</header>

<section id="abstract" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="abstract"><span class="header-section-number">1.1</span> Abstract</h2>
<p>My project surveys the development of <em>Janson’s History of Art</em> across its eight editions as well as <em>Gardner’s Art Through the Ages</em> through its sixteen editions, looking particularly at the change in artist demographic through time. Additionally, this paper investigates which external variables such as artist gender, ethnicity, race, nationality, number of exhibitions at the Museum of Modern Art, and number of exhibitions at The Whitney if any, help predict the magnitude of an artist’s inclusion in art history survey texts. I conduct data analysis to assess the demographic representation of artists through editions of <em>Janson’s History of Art</em> and <em>Gardner’s Art Through the Ages</em>, a proxy for the art history survey. I compare artist demographics through editions of Janson and Gardner. My findings indicate that coverage of minority artists (defined as non-white and/or Hispanic or Latinx and/or female) increases across editions of <em>Janson’s History of Art</em> and <em>Gardner’s Art Through the Ages</em>, but remains negligible compared to white male non-Hispanic or Latinx artists. Moreover, in <em>Janson’s History of Art</em> through all editions, the percentage of artists who are white is 97.37%, the percentage of artists that are male is 89.99%, and the percentage of artists that are not Hispanic or Latinx is 95.82%. In <em>Gardner’s Art Through the Ages</em>, through all editions, the percentage of artists who are white is 90.02%, the percentage of artists that are male is 85.69%, and the percentage of artists that are not Hispanic or Latinx is 91.51%. Both texts display a narrative of the history of art as being predominantly white, male, non-Hispanic or Latinx. Regarding nationality, in Janson, 78.51% of the artists are American, British, French, German, and Spanish, which is very similar to Gardner’s 76.58% of those five same nationalities. I have chosen to run a linear mixed-effects model with a random effect of the artist’s name, to infer the magnitude of the space given to a particular artist divided by the area of the page of the given edition (total space ratio per page), in <em>Janson’s History of Art</em> and <em>Gardner’s Art Through the Ages,</em> using the potential predictor variables: Artist Race, Artist Gender, Artist Ethnicity, Artist Nationality, the count through time of the number of exhibitions an artist has at the MoMA, and the count through time of the number of exhibitions an artist has at The Whitney. The model that best explains the variance in the total space ratio per page per artist per edition uses artist nationality and the count through time of the number of exhibitions an artist has in the MoMA as well as the interaction between those two variables. With a log transformation applied to the outcome variable of the as it is heavily right-skewed, my linear mixed-effects model yields a conditional r squared of 53.23%. Such denotes that 53.23% of the variance of total space ratio per page given to an artist in a given edition can be explained by the artist’s nationality and the count through time of the number of exhibitions an artist has at the MoMA.</p>
<p>JEL Numbers: C80, Y10, Z11</p>
<p>Key Words: Cultural Economics, Art History, Statistics, Historiography, Data Collection Methodology, Linear Mixed-Effects Modeling.</p>
<p>Data Preparation:</p>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<p>ddf=“Satterthwaite”¶</p>
<p>Satterthwaite test, more flexible, looking directly at p-values - non-parametric test - uses different error term, similar to a two same t-test, similar to ANOVA - analysis of variance - checking between different groups -</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-stdout">
<pre><code>Backward reduced random-effect table:

                  Eliminated npar  logLik    AIC    LRT Df Pr(&gt;Chisq)    
&lt;none&gt;                         22 -1407.2 2858.3                         
(1 | artist_name)          0   21 -2255.3 4552.6 1696.2  1  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Backward reduced fixed-effect table:
Degrees of freedom method: Satterthwaite 

                                            Eliminated  Sum Sq Mean Sq NumDF
artist_race_nwi:moma_count_to_year                   1 0.00575 0.00575     1
artist_ethnicity:whitney_count_to_year               2 0.00836 0.00836     1
artist_race_nwi:whitney_count_to_year                3 0.06087 0.06087     1
artist_race_nwi                                      4 0.01434 0.01434     1
artist_gender                                        5 0.08807 0.08807     1
artist_ethnicity:moma_count_to_year                  6 0.09505 0.09505     1
artist_ethnicity                                     7 0.01452 0.01452     1
whitney_count_to_year                                0 0.94957 0.94957     1
artist_nationality_other:moma_count_to_year          0 2.56307 0.51261     5
                                              DenDF F value    Pr(&gt;F)    
artist_race_nwi:moma_count_to_year           533.82  0.0499 0.8232618    
artist_ethnicity:whitney_count_to_year      2174.81  0.0726 0.7876537    
artist_race_nwi:whitney_count_to_year        497.70  0.5282 0.4677161    
artist_race_nwi                              484.81  0.1244 0.7244730    
artist_gender                                415.45  0.7640 0.3825716    
artist_ethnicity:moma_count_to_year          675.27  0.8247 0.3641252    
artist_ethnicity                             486.16  0.1259 0.7228281    
whitney_count_to_year                       1091.60  8.2366 0.0041846 ** 
artist_nationality_other:moma_count_to_year 1425.16  4.4464 0.0005048 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Model found:
log(space_ratio_per_page_total) ~ artist_nationality_other + moma_count_to_year + whitney_count_to_year + (1 | artist_name) + artist_nationality_other:moma_count_to_year</code></pre>
</div>
</div>
<p>pick a handful of interest</p>
<p>visualization : confidence intervals for each on of the slopes</p>
<p>predictors on the y axis -</p>
<p>bar plots of the pvalues another option</p>
<p>nationality discourse for significance</p>
<p>log transformation on the y variable -</p>
<p>stepwise model selection</p>
<p>the multiple of the number of degrees of freedom used for the penalty. Only k = 2 gives the genuine AIC: k = log(n) is sometimes referred to as BIC or SBC.</p>
<div class="cell">
<div class="cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite's
  method [lmerModLmerTest]
Formula: log(space_ratio_per_page_total) ~ artist_nationality_other +  
    moma_count_to_year + artist_nationality_other * moma_count_to_year +  
    (1 | artist_name)
   Data: gardnerjanson_museums_mod

     AIC      BIC   logLik deviance df.resid 
  2853.1   2937.6  -1412.5   2825.1     3090 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.8692 -0.5597 -0.0344  0.5743  3.6926 

Random effects:
 Groups      Name        Variance Std.Dev.
 artist_name (Intercept) 0.1105   0.3324  
 Residual                0.1156   0.3400  
Number of obs: 3104, groups:  artist_name, 394

Fixed effects:
                                                      Estimate Std. Error
(Intercept)                                         -1.066e+00  6.950e-02
artist_nationality_otherAmerican                     7.793e-02  7.843e-02
artist_nationality_otherFrench                       3.108e-01  8.291e-02
artist_nationality_otherOther                        1.954e-02  7.943e-02
artist_nationality_otherBritish                      6.277e-02  9.446e-02
artist_nationality_otherSpanish                      6.485e-01  1.928e-01
moma_count_to_year                                   1.101e-02  4.905e-03
artist_nationality_otherAmerican:moma_count_to_year -2.203e-02  7.874e-03
artist_nationality_otherFrench:moma_count_to_year    1.106e-03  5.939e-03
artist_nationality_otherOther:moma_count_to_year    -6.692e-03  6.115e-03
artist_nationality_otherBritish:moma_count_to_year  -8.244e-03  1.452e-02
artist_nationality_otherSpanish:moma_count_to_year   9.606e-03  7.324e-03
                                                            df t value Pr(&gt;|t|)
(Intercept)                                          4.588e+02 -15.331  &lt; 2e-16
artist_nationality_otherAmerican                     4.651e+02   0.994 0.320904
artist_nationality_otherFrench                       4.396e+02   3.748 0.000202
artist_nationality_otherOther                        4.714e+02   0.246 0.805742
artist_nationality_otherBritish                      4.403e+02   0.665 0.506703
artist_nationality_otherSpanish                      3.713e+02   3.364 0.000847
moma_count_to_year                                   1.647e+03   2.245 0.024928
artist_nationality_otherAmerican:moma_count_to_year  1.125e+03  -2.798 0.005228
artist_nationality_otherFrench:moma_count_to_year    1.866e+03   0.186 0.852305
artist_nationality_otherOther:moma_count_to_year     1.325e+03  -1.094 0.274068
artist_nationality_otherBritish:moma_count_to_year   9.461e+02  -0.568 0.570410
artist_nationality_otherSpanish:moma_count_to_year   2.773e+03   1.312 0.189784
                                                       
(Intercept)                                         ***
artist_nationality_otherAmerican                       
artist_nationality_otherFrench                      ***
artist_nationality_otherOther                          
artist_nationality_otherBritish                        
artist_nationality_otherSpanish                     ***
moma_count_to_year                                  *  
artist_nationality_otherAmerican:moma_count_to_year ** 
artist_nationality_otherFrench:moma_count_to_year      
artist_nationality_otherOther:moma_count_to_year       
artist_nationality_otherBritish:moma_count_to_year     
artist_nationality_otherSpanish:moma_count_to_year     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) art__A art__F art__O art__B art__S mm_c__ a__A:_ a__F:_
artst_ntn_A -0.886                                                        
artst_ntn_F -0.838  0.743                                                 
artst_ntn_O -0.875  0.775  0.734                                          
artst_ntn_B -0.736  0.652  0.617  0.644                                   
artst_ntn_S -0.361  0.320  0.302  0.316  0.265                            
mm_cnt_t_yr -0.311  0.276  0.261  0.272  0.229  0.112                     
arts__A:___  0.194 -0.334 -0.163 -0.170 -0.143 -0.070 -0.623              
arts__F:___  0.257 -0.228 -0.294 -0.225 -0.189 -0.093 -0.826  0.514       
arts__O:___  0.250 -0.221 -0.209 -0.315 -0.184 -0.090 -0.802  0.500  0.662
arts__B:___  0.105 -0.093 -0.088 -0.092 -0.289 -0.038 -0.338  0.210  0.279
arts__S:___  0.208 -0.185 -0.175 -0.182 -0.153 -0.302 -0.670  0.417  0.553
            a__O:_ a__B:_
artst_ntn_A              
artst_ntn_F              
artst_ntn_O              
artst_ntn_B              
artst_ntn_S              
mm_cnt_t_yr              
arts__A:___              
arts__F:___              
arts__O:___              
arts__B:___  0.271       
arts__S:___  0.537  0.226</code></pre>
</div>
</div>
</section>
<section id="introduction-and-context" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introduction and Context</h1>
<section id="inspiration-for-research" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="inspiration-for-research"><span class="header-section-number">2.1</span> Inspiration for Research:</h2>
<p>Heading into the second semester of my junior year, I scheduled a zoom meeting with my now undergraduate thesis advisor, Prof.&nbsp;Hans van Miegroet, to ask a few questions about my aspirations after college. He had been my professor for his course, “History of Art Markets,” a learning experience at Duke that has permanently altered my worldview. The meeting began with me expressing my enjoyment of the course, and the appreciation of the discussion of transparency in the buying and selling of art. I asked his opinion of whether I should stick to studying architectural history with hopes of going to architecture school, or pivot to do further research under him in his graduate course, “Arts and Markets” that I had enrolled in for that Spring. Towards the end of the meeting, he asked me what I found most interesting about art, to which I replied, “Ever since I took my first Art History course, I’ve always been curious as to why I am introduced to the works I am. Who is choosing what I study versus what I don’t study?” I explained to him. I had initially learned the story of art through Marilyn Stokstad’s, <em>Art History</em> my final year of high school. At the end of that school year, I inquired to my teacher, Carolyn Paczkowska, in a class discussion, “Why are we studying the works that we have?” The class discussed gatekeepers of art and information and later ended in the conclusion of uncertainty. Prof.&nbsp;van Miegroet looked at me through the computer screen and stated I had found my research question for my Undergraduate Honors Thesis, that I had found my why.</p>
<p>My research began solely looking at how art history textbooks changed through time, then developed into looking at using a linear mixed-effect model with a log transformation on my outcome variable to infer which external variables would if at all work to predict the magnitude of space (of text and of the figure of their work or works) given to an artist in a given book.</p>
</section>
<section id="why-gardners-art-through-the-ages" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="why-gardners-art-through-the-ages"><span class="header-section-number">2.2</span> Why <em>Gardner’s Art Through the Ages:</em></h2>
<section id="discourse-of-authorship" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="discourse-of-authorship"><span class="header-section-number">2.2.1</span> Discourse of Authorship:</h3>
</section>
<section id="literature-review" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="literature-review"><span class="header-section-number">2.2.2</span> Literature Review:</h3>
<p><strong>(</strong>Discourse of dominance through time of the text, find and add sources and if available sales information through time)</p>
<p>REACH OUT FOR SALES DATA TO PUBLISHERS</p>
<p>Britannica</p>
<ul>
<li>The lack of a <a href="https://www.merriam-webster.com/dictionary/comprehensive">comprehensive</a> single-volume textbook on art history prompted Gardner to write one herself, and the resulting Art Through the Ages (1926) far surpassed other available works in readability, breadth of coverage, and wealth of illustration. It remained a widely used text for decades. In 1932 she published Understanding the Arts, aimed at a wide general audience. A second edition of Art Through the Ages, greatly expanded, appeared in 1936; <strong>the first two editions sold more than 260,000 copies.</strong> Gardner had been named an assistant professor in the Art Institute school in 1929, and in 1933 she became a professor and head of the department of art history. She retired from the Art Institute school in 1943. Despite declining health she managed to complete work on the manuscript of a third edition of Art Through the Ages (published in 1948).</li>
</ul>
<p>Sources Found to Looking Into:</p>
<ul>
<li>Franciscono, Marcel.
<ol start="1977" type="1">
<li>“History, Textbooks, and Art: Reflections on a Half Century of Helen Gardner’s”Art through the Ages”.” Critical Inquiry 4 (2) (Winter): 285. https://login.proxy.lib.duke.edu/login?u rl=https://www.proquest.com/scholarly-journals/history-textbooks-art-reflections-on-half-century/docview/1297337757/se-2?a ccountid=10598.</li>
</ol></li>
<li>Jaffee, Barbara. “9.”Gardner” Variety Formalism: Helen Gardner and Art through the Ages” In Partisan Canons edited by Anna Brzyski, 203-224. New York, USA: Duke University Press, 2007. https://doi.org/10.1515/9780822390374-010.</li>
</ul>
<p><strong>Table 1:</strong> Edition Number, Year of Publication, Title, Authorship, and Publisher Over Time of All Cataloged Editions of Gardner’s Art Through the Ages.</p>
<table class="table">
<colgroup>
<col style="width: 4%">
<col style="width: 8%">
<col style="width: 37%">
<col style="width: 27%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Edition</th>
<th>Year of Publication</th>
<th>Author(s)</th>
<th>Title</th>
<th>Publisher (as listed per Edition)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1926</td>
<td>Helen Gardner</td>
<td>Art Through the Ages; An Introduction to Its History and Significance</td>
<td>New York, Brace, Harcourt</td>
</tr>
<tr class="even">
<td>2</td>
<td>1936</td>
<td>Helen Gardner</td>
<td>Art Through the Ages; An Introduction to Its History and Significance</td>
<td>New York, Brace, Harcourt</td>
</tr>
<tr class="odd">
<td>3</td>
<td>1948</td>
<td>Helen Gardner</td>
<td>Art Through the Ages</td>
<td>New York, Brace, Harcourt</td>
</tr>
<tr class="even">
<td>4</td>
<td>1959</td>
<td>Helen Gardner; revised by Sumner M. Crosby and the Dept. of the History of Art, Yale University</td>
<td>Art Through the Ages</td>
<td>New York, Harcourt, Brace</td>
</tr>
<tr class="odd">
<td>5</td>
<td>1970</td>
<td>Revised by Horst de la Croix, Richard G. Tansey</td>
<td>Gardner’s Art Through the Ages</td>
<td>New York, Harcourt, Brace</td>
</tr>
<tr class="even">
<td>6</td>
<td>1975</td>
<td>Helen Gardner; revised by Horst de la Croix, Richard G. Tansey</td>
<td>Gardner’s Art Through the Ages</td>
<td>New York: Harcourt Brace Jovanovich</td>
</tr>
<tr class="odd">
<td>7</td>
<td>1980</td>
<td>Helen Gardner; revised by Horst de la Croix, Richard G. Tansey</td>
<td>Gardner’s Art Through the Ages</td>
<td>Harcourt Brace Jovanovich, New York</td>
</tr>
<tr class="even">
<td>8</td>
<td>1986</td>
<td>Horst de la Croix, Richard G. Tansey</td>
<td>Gardner’s Art Through the Ages</td>
<td>Harcourt Brace Jovanovich, San Diego, CA</td>
</tr>
<tr class="odd">
<td>9</td>
<td>1991</td>
<td>Horst de la Croix, Richard G. Tansey, Diane Kirkpatrick</td>
<td>Gardner’s Art Through the Ages</td>
<td>San Diego: Harcourt Brace Jovanovich</td>
</tr>
<tr class="even">
<td>10</td>
<td>1996</td>
<td>Richard G. Tansey, Fred S. Kleiner</td>
<td>Gardner’s Art Through the Ages</td>
<td>Fort Worth, TX: Harcourt Brace</td>
</tr>
<tr class="odd">
<td>11</td>
<td>2001</td>
<td>Fred S. Kleiner, Christin J. Mamiya, Richard G. Tansey</td>
<td>Gardner’s Art Through the Ages</td>
<td>Fort Worth TX: Harcourt College Publishers</td>
</tr>
<tr class="even">
<td>12</td>
<td>2005</td>
<td>Fred S. Kleiner, Christin J. Mamiya</td>
<td>Gardner’s Art Through the Ages</td>
<td>Thomson/Wadsworth, Belmont, CA</td>
</tr>
<tr class="odd">
<td>13</td>
<td>2009</td>
<td>Fred S. Kleiner</td>
<td>Gardner’s Art Through the Ages: A Global History</td>
<td>Boston, Thomson/Wadsworth</td>
</tr>
<tr class="even">
<td>14</td>
<td>2013</td>
<td>Fred S. Kleiner</td>
<td>Gardner’s Art Through the Ages: A Global History</td>
<td>Australia ; United States : Wadsworth, Cengage Learning</td>
</tr>
<tr class="odd">
<td>15</td>
<td>2016</td>
<td>Fred S. Kleiner</td>
<td>Gardner’s Art Through the Ages: A Global History</td>
<td>Boston, MA : Cengage Learning</td>
</tr>
<tr class="even">
<td>16</td>
<td>2020</td>
<td>Fred S. Kleiner</td>
<td>Gardner’s Art Through the Ages: A Global History</td>
<td>Boston, MA, US : Cengage Learning</td>
</tr>
</tbody>
</table>
<p><strong>Table 4:</strong> Authors of Gardner’s Art Through the Ages: NEEDS TO BE ADDED</p>
<table class="table">
<colgroup>
<col style="width: 11%">
<col style="width: 24%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Author Name</th>
<th>Edition Number (Year)</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sumner McKnight Crosby (1909-1982)</td>
<td>4 (1959)</td>
<td>Sumner McKnight Crosby was an American Medievalist architectural historian. He was the principal scholar of St-Denis and chair of the Department of Art History, Yale University, 1947-1953.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></td>
</tr>
<tr class="even">
<td>Horst de la Croix</td>
<td>5 (1970), 6 (1975), 7 (1980), 8 (1986), 9 (1991)</td>
<td></td>
</tr>
<tr class="odd">
<td>Richard G. Tansey</td>
<td>5 (1970), 6 (1975), 7 (1980), 8 (1986), 9 (1991), 10 (1995)</td>
<td></td>
</tr>
<tr class="even">
<td>Diane Kirkpatrick</td>
<td>9 (1991)</td>
<td></td>
</tr>
<tr class="odd">
<td>Fred S. Kleiner</td>
<td>10 (1995), 11 (2001), 12 (2005), 13 (2009), 14 (2013), 15 (2016), 16 (2020)</td>
<td></td>
</tr>
<tr class="even">
<td>Christin J. Mamiya</td>
<td>11 (2001), 12 (2005)</td>
<td></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="why-jansons-history-of-art" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="why-jansons-history-of-art"><span class="header-section-number">2.3</span> Why <em>Janson’s History of Art</em>:</h2>
<p>Such a text is claimed to be the most influential art history survey through time by myriad art historians such as Jeffery Wiedman, Zoë Ingalls, John Russell, Alexandra Peers, Elizabeth Sears and Charlotte Schoell-Glass to name a few. Alexandra Peers in her publication for ARTnews.com in February of 2006, claims that “it was Janson who, more than any other art historian, pioneers the ‘in and out’ celebrity model of art history. There were artists who matter, he argued, and those who didn’t.”<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> Janson’s formation of his history of art is not only arguably the most dominant art history survey over time, but also he holds a reputation of being a gatekeeper of art history. He states at the end of his introduction in the first and second editions that after having read his text, one “shall have joined the active minority that participates directly in shaping the course of art in our time.”<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> He recognizes his role as an individual who shapes the narrative of the history of art, while convincing the reader that after having read his text, one has the agency to be a gatekeeper alongside him . Such agency is only granted once one understands his digestion of the most important works and artists through time .</p>
<p>It would be most comprehensive if we were to have access to the total number of sales per edition of Janson’s History of Art, to use as tangible data to show the relevance and importance of the text through time. Both publishers, Harry N. Abrams and Prentice-Hall (now Pearson Prentice-Hall) have declined sharing sales information in the aggregate. By leafing through various scholarly publications, there is imperfect data of sale information worth noting when discussing the dominance of Janson’s History of Art through time. The text was at its height of sales between when it was initially released in 1962 through H. W. “Peter” Janson’s death in 1982 (refer to Table 1 for complete information of each edition). Art historian, Patricia Hills cites in her publication in Artforum, “in 1973 the Janson text had 46% of the market, while Gardner’s 5th edition had 24%, followed by Gombrich’s, 8.5%, Cleaver with 3% and miscellaneous ‘other’ with 18.5%.”<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> At the time such a report had been made, the first edition (1962), the first edition revised and enlarged (1969) had been released. Additionally, it was written by John Russell of the New York Times in October of 1982 that “well over two million copies have been sold.”<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> Russell does not specify whether these sales numbers are solely the first edition of Janson’s History of Art, or the first edition as well as the first edition revised and enlarged and the second edition (1977) . He also added that the text had been “translated in 14 languages and is widely regarded as both an essential teaching instrument and a book that can be read and looked at with continuous enjoyment.”<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> Here, Russell perpetuates the significance of Janson’s survey, as well as providing information about the breadth of Janson’s text, reaching more than solely English-reading audience s.</p>
<p>Conversely, Zoë Ingalls in a publication in August of 1995 discussing Janson’s relevance through time, cites that “the first edition sold more than a million copies.”<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> Though there are informational discrepancies, it is clear that Janson’s History of Art was prolific as a survey text of art for over 20 years. The narrative remained significant from the third (1986) through the fifth edition (1995), which were all revised by Anthony “Tony” F. Janson, son of Peter and Dora Jane. Ingalls states that “the fourth edition, published in 1991, sold 21,000 copies the first year and an average of 11,000 copies a year in the past four years. The new fifth edition, has sold more than 13,000 copies since its March release.”<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> She continues, “Although its sales have been eclipsed over the last 10 years by another perennial favorite, R.H. Gardner’s Art Through the Ages, Janson is still the standard in many people’s minds.”<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> Notably, she does not mention any total sales information about Gardner’s survey text, just that over the past decade (1985-1995), its sales trumped that of Janson’ s.</p>
<p>After the sixth edition (2001) and the sixth edition revised (2004) the last with authorship by Tony Janson, Harry N. Abrams and Prentice Hall were unsatisfied by the total sales, as well as the overall structure and content of the text as they were criticized for having lost touch with young readers.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a> At the same moment, Harry N. Abrams sold all rights to the newly formed Pearson Prentice Hall, who recruited new authorship of six various art historians across the United States: Penelope J. E. Davies, Walter B. Denny, Frima Fox Hofrichter, Joseph Jacobs, Ann M. Roberts, and David L. Simon (refer to Table 2). Such change was received negatively by art historians, which is reflected in the text’s further decline in sales. <a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a> It has been estimated by Bookauthority.com (a cite whose source for this information is very unclear) that the eighth edition revised, published in 2015 has had 2,000 total copies sold, while competing art historical narratives such as Marilyn Stokstad and Micheal W. Cothren’s History of Art Vol . 1 has had an estimated 10,000 copies sold since its release in 2017 .<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a> Such has left Janson’s History of Art as a minor player in art historical narratives today.</p>
<p><strong>Table 2:</strong> Edition Number, Year of Publication, Title, Authorship, and Publisher Over Time of All Cataloged Editions of Janson’s History of Art.</p>
<table class="table">
<colgroup>
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 31%">
<col style="width: 27%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Edition Number</th>
<th>Year of Publication</th>
<th>Authors</th>
<th>Title</th>
<th>Publisher (as listed per Edition)<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1963<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a></td>
<td>H.W. Janson with Dora Jane Janson<a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a></td>
<td>History of Art: A Survey of the Major Visual Arts from the Dawn of History to the Present Day</td>
<td>Harry N. Abrams, Inc., New York</td>
</tr>
<tr class="even">
<td>1 (Revised and Enlarged)</td>
<td>1969</td>
<td>H. W. Janson with Dora Jane Janson</td>
<td>History of Art: A Survey of the Major Visual Arts from the Dawn of History to the Present Day</td>
<td>Prentice-Hall Inc., Englewood Cliffs, New Jersey and Harry N. Abrams, Inc., New York.</td>
</tr>
<tr class="odd">
<td>2</td>
<td>1977</td>
<td>H. W. Janson with Dora Jane Janson</td>
<td>History of Art: A Survey of the Major Visual Arts from the Dawn of History to the Present Day</td>
<td>Harry N. Abrams, Inc., New York.</td>
</tr>
<tr class="even">
<td>3</td>
<td>1986</td>
<td>H. W. Janson; Revised and Expanded by Anthony F. Janson</td>
<td>History of Art</td>
<td>Harry N. Abrams, Inc., New York and Prentice-Hall Inc., Englewood Cliffs, New Jersey.&nbsp;</td>
</tr>
<tr class="odd">
<td>4</td>
<td>1991</td>
<td>H. W. Janson; Revised and Expanded by Anthony F. Janson</td>
<td>History of Art</td>
<td>Harry N. Abrams, Inc., New York.</td>
</tr>
<tr class="even">
<td>5</td>
<td>1995</td>
<td>H. W. Janson; Revised and Expanded by Anthony F. Janson</td>
<td>History of Art</td>
<td><p>Harry N. Abrams, Inc., New York.</p>
<p><br>
</p></td>
</tr>
<tr class="odd">
<td>6</td>
<td>2001</td>
<td>H. W. Janson and Anthony F. Janson</td>
<td>History of Art</td>
<td><p>Harry N. Abrams, Inc., New York.</p>
<p><br>
</p></td>
</tr>
<tr class="even">
<td>7</td>
<td>2007</td>
<td>Penelope J. E. Davies, Walter B. Denny, Frima Fox Hofrichter, Joseph Jacobs, Ann M. Roberts, David L. Simon</td>
<td>Janson’s History of Art: The Western Tradition</td>
<td>Pearson Prentice Hall, Upper Saddle River, New Jersey.</td>
</tr>
<tr class="odd">
<td>8</td>
<td>2011</td>
<td>Penelope J. E. Davies, Walter B. Denny, Frima Fox Hofrichter, Joseph Jacobs, Ann M. Roberts, David L. Simon</td>
<td>Janson’s History of Art: The Western Tradition</td>
<td>Pearson Prentice Hall, Upper Saddle River, New Jersey.</td>
</tr>
</tbody>
</table>
<section id="discourse-of-authorship-through-editions" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="discourse-of-authorship-through-editions"><span class="header-section-number">2.3.1</span> <strong>Discourse of Authorship Through Editions:</strong></h3>
<p>The primary author through the first six editions of Janson’s History of Art is Horace Waldemar Janson (1913-1982), colloquially referred to as Peter. He was born in 1913 in St.&nbsp;Petersburg, Russia. His parents were of Swedish and Latvian descent. The family moved to Hamburg, Germany after the Russian Revolution. Janson studied at Munich and then at the University in Hamburg where he was a student of Erwin Panofsky, a prolific art historian known for his contributions to the studies of symbols and iconography in art. In 1935, at the suggestion of his advisor, Janson fled Germany under the sponsorship of Alfred Barr, director of the Museum of Modern Art in New York. Janson studied at Harvard between 1935 and 1942, completing a PhD in art history. His most significant professorial position began in 1949, where he was appointed professor and later chairman of the department of art at New York University. He remained in such a role for 25 years as he grew the department’s prestige, solidifying its reputation as one of the most conservative art history programs in the country. A decade later, in 1959, Janson issued a book titled, Key Monuments of the History of Art, in efforts to aid his undergraduates in their study of art as the availability of good personal study images were not easily accessible. Such publication sparked Janson’s History of Art released in 1962, a survey of art written with his wife, Dora Jane Janson.</p>
<p><br>
Born Dora Jane Heineberg (1916-2002) in Philadelphia in 1916, she shared a passion for art with Peter. The two met in Cambridge, Massachusetts as she attended Radcliffe College as an undergraduate student while Janson was studying at Harvard. Dora Jane Janson worked with her husband on many publications, but her most notable achievement came in 1971 when she wrote an exhibition catalog for the Nasher Museum of Art at Duke on Art Nouveau jewelry, titled From Slave to Siren: The Victorian Woman and Her Jewelry from Neoclassic to Art Nouveau. Authorship of Janson’s History of Art was handed over to one of the couple’s four children, Anthony F. Janson, after the sudden passing of Peter Janson in 1982.</p>
<p>Anthony Frederick “Tony” Janson was born March 30th, 1943 in St.&nbsp;Louis, Missouri. The Jansons moved to New York in 1949, and Tony Janson frequently visited the city’s museums as a child and teenager. In 1954, the Jansons spent a year in Europe. In an interview, Tony Janson describes his attitude upon the family’s return to New York as one of ” total rebellion” eventually causing his parents to search for a school that would engage him better academically.<a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a> Janson details how he rediscovered a love for learning after enrolling at Riverdale Country School on a full scholarship, and it is at this time that he began to study art history. Janson experimented as an artist himself, and cited his early affection for photography as the reason he was the first to add that medium to a survey textbook of art history. <a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a> Educated at Columbia and Harvard, Janson was asked to continue the work of his father as author of Janson’s History of Art . Unable to revise the entire textbook in time, Janson “added women, which was long overdue.”<a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a> and photography to the textbook for the third editio n.&nbsp;After returning from the Vietnam War, Janson earned his PhD in art history from Harvard and went to teach at the College of Charleston before transitioning to a career as chief curator of the Indianapolis Museum of Ar t. In 1984 Janson moved to the Ringling Museum of Art in Sarasota, Florida, and then he was Chief Curator of the North Carolina Museum of Art from 1989 to 199 3. Janson spent the rest of his career at UNC Wilmington and retired in 200 2. The last edition of Janson’s History of Art that he worked on was the sixth revised, and he viewed his revisions of Janson’s History of Art as more in line with his father’s approach than the rest of his own scholarshi p.</p>
<p>The seventh and eighth editions were rewritten by a group of art historians across the United States: Penelope J. E. Davies, Walter B. Denny, Frima Fox Hofrichter, Joseph Jacobs, Ann M. Roberts, and David L. Simon. In Table 2, each author’s name, gender, ethnicity and nationality are listed, with question marks next to Frima Fox Hofrichter and Ann M. Roberts’ nationality and Joseph Jacob’s ethnicity as such information could not be found with full certainty. We observe here a desire to diversify authorship in efforts by the publisher to cater to young readership, and increase sales. Notably, there is gender diversity, with a fifty-fifty split of male to female authorship, though a complete lack of racial diversity, which is a notion reflected additionally in the text itself. Since the Janson name has left the book’s authorship, the text has declined significantly from being the most dominant art historical survey.<a href="#fn19" class="footnote-ref" id="fnref19" role="doc-noteref"><sup>19</sup></a></p>
<p><strong>Table 3:</strong> Authors of the Seventh and Eighth Editions of Janson’s History of Art.</p>
<table class="table">
<colgroup>
<col style="width: 7%">
<col style="width: 92%">
</colgroup>
<thead>
<tr class="header">
<th>Author</th>
<th>Description (As listed by Publisher)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p>Penelope J. E. Davies</p>
<p><br>
</p></td>
<td>Associate Professor at the University of Texas, Austin. She is a scholar of Greek and Roman art and architecture as well as a field archaeologist. She is an author of Death and the Emperor: Roman Imperial Funerary Monuments from Augustus to Marcus Aurelius, and winner of the Vasari Award.</td>
</tr>
<tr class="even">
<td>Walter B. Denny</td>
<td>Professor of Art History at the University of Massachusetts at Amherst. In addition to exhibition catalogues, his publications include books on Ottoman Turkish carpets, textiles, and ceramics, and articles on miniature painting, architecture and architectural decoration.</td>
</tr>
<tr class="odd">
<td>Frima Fox Hofrichter</td>
<td>Professor and former Chair of the History of Art and Design department at Pratt Institute. She is the author of Judith Leyster, A Dutch Artist in Holland’s Golden Age, which received CAA’s Millard Meiss Publication Fund Award.</td>
</tr>
<tr class="even">
<td>Joseph Jacobs</td>
<td>An independent scholar, critic, and art historian of modern art in New York City. He was the curator of modern art at the John and Mable Ringling Museum of Art in Sarasota, Florida, director of the Oklahoma City Art Museum, and curator of American art at The Newark Museum, Newark, New Jersey.</td>
</tr>
<tr class="odd">
<td>Ann M. Roberts</td>
<td>Professor of Art at Lake Forest College, she has published essays, articles and reviews on both Northern and Italian Renaissance topics. Her research focuses on women in the Renaissance, and her most recent publication is entitled Dominican Women and Renaissance Art: The Convent of San Domenico of Pisa.</td>
</tr>
<tr class="even">
<td>David L. Simon</td>
<td>Jetté Professor of Art at Colby College where he received the Basset Teaching Award in 2005. Among his publications is the catalogue of Spanish and southern French Romanesque sculpture in the Metropolitan Museum of Art and The Cloisters.</td>
</tr>
</tbody>
</table>
</section>
<section id="literature-review-1" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="literature-review-1"><span class="header-section-number">2.3.2</span> <strong>Literature Review:</strong></h3>
<p>Many are Culled but Few are Chosen: Janson’s History of Art, Its Reception, Emulators, Legacy, and Current Demise</p>
<p>The publication by art historian Jeffrey Weidman, released in January, 2007 in the Journal of Scholarly Publishing begins by reviewing in detail the lineage of English-language art history surveys in America, and the Jansons’ text therein; discusses in detail the various reviews of the Jansons’ and other survey texts, namely Helen Gardner’s <em>Art Through the Ages</em>, and Marilyn Stokstad et al.’s <em>Art History.</em><a href="#fn20" class="footnote-ref" id="fnref20" role="doc-noteref"><sup>20</sup></a> He concludes that Janson’s History of Art functioned as the dominant art history survey through time. Secondly, Weidman discusses the changes of Janson’s History of Art between the sixth edition revised, the last edition written by Peter and Tony Janson, and the seventh edition written by the six various art historians (Table 2). He believes that the seventh edition is a disgrace to Janson’s text, and the beauty of Janson’s analytically writing has been completely stripped in the seventh edition. He also discusses, yet only through a handful of examples, artists and works which were taken out as well as added between the sixth edition revised and the seventh (for a comprehensive understanding of artists taken out and added through time refer to Fig. __). Notably, such publication does not discuss data in the aggregate when looking at who is included and excluded, and rather only looks in detail at the changes between the sixth edition revised and the seventh edition.</p>
<p>Revising Art History’s Big Book: Who’s In and Who Comes Out?</p>
<p>This article published by Randy Kennedy in March of 2006 in the New York Times, also discusses the change between the sixth edition revised and the seventh edition of Janson’s <em>History of Art</em>.<a href="#fn21" class="footnote-ref" id="fnref21" role="doc-noteref"><sup>21</sup></a> Kennedy looks at only a few artists and works who leave and are added, particularly baffled by the exclusion of James Abbot McNeill Whistler’s Arrangement in Black and Gray: The Artist’s Mother. He interviews Sarah Touburg, an editor of the seventh edition who claims that upwards of 25% of the book’s content had been altered between the sixth edition revised and the seventh edition. Interestingly, Kennedy claims that the new book adds more women and it uses art much more as a way to discuss race, class and gender. Such an observation is not reflected in our data, which can be seen in figures __, ___, and ___. This publication also discusses the dominance and influence that Janson’s History of Art has had over time, as well as its decline as the best-selling art survey in recent years. Kennedy states that a shift in authorship was done in efforts to revitalize Janson’s relevance to younger audiences. Though this publication discusses the change between two editions, Kennedy does not do so in the aggregate.<br>
</p>
<p>Discussions and Depictions of Women in H. W. Janson’s History of Art, Fourth Edition</p>
<p>Art historian Paul E. Bolin discusses gender inequality through the first four editions of <em>Janson’s History of Art.</em><a href="#fn22" class="footnote-ref" id="fnref22" role="doc-noteref"><sup>22</sup></a> He states that a primary criticism of Janson’s text is its lack of attention given to the importance of work of women artists. The first two editions did not include any women, then there was an influx of female artists when Tony Janson claimed primary authorship for the publication of the third edition in 1986. Bolin argues that even with the edition of female artists in the third and fourth editions, there is still not enough representation and that additionally the fashion in which Tony discusses female artists is apologetic and at times problematic. Bolin uses simple statistics in his discourse, having counted a total of 9 out of the 28 new artists added to the fourth edition as female. Bolin does not discuss racial discrimination, nor does he use complete data in the aggregate when looking gender discrimination.</p>
</section>
</section>
</section>
<section id="significance-of-research" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> <strong>Significance of Research:</strong></h1>
<p>As far as I am aware, there has not been research done in the aggregate, quantitatively analyzing the change over time specifically regarding artist demographic in <em>Janson’s History of Art</em> nor <em>Gardner’s Art Through the Ages</em>. My research is significant as it efficiently shows the gaps of representation in terms of gender, nationality, race, and ethnicity that have not been deeply touched on by previous scholars. As mentioned in my literature review of publications that discuss <em>Gardner’s Art Through the Ages,</em> the closest research I have found to my own was published by The University of Chicago Press Journals in 2020 in which two professors and library assistant out of Purdue University, randomly selected and cataloged information from the first, fifth, twelfth and sixteenth edition. They were focused on how the length of the book changes through time, the type of image changed through time, how the percent of color images change through time, and how the number of suggested readings changes through time. My research has more breadth, as I scraped information from all 16 editions of <em>Gardner’s Art Through the Ages,</em> as well as <em>Janson’s History of Art</em> and working less with how the book itself was changing, but more so how the artist’s included changes through time.</p>
<p>Secondly, my research looks at how the area given to particular artists changes through time and which, if any, external variables can help account for the variance of such. As mentioned in my abstract, I use a linear mixed-effects model with a random effect of the artist’s name, to infer the magnitude of the space given to a particular artist divided by the area of the page of the given edition (total space ratio per page), in <em>Janson’s History of Art</em> and <em>Gardner’s Art Through the Ages,</em> using the potential predictor variables: Artist Race, Artist Gender, Artist Ethnicity, Artist Nationality, the count through time of the number of exhibitions an artist has at the MoMA, and the count through time of the number of exhibitions an artist has at The Whitney. The model that best explains the variance in the total space ratio per page per artist per edition uses artist nationality and the count through time of the number of exhibitions an artist has in the MoMA as well as the interaction between those two variables. With a log transformation applied to the outcome variable of the as it is heavily right-skewed, my linear mixed-effects model yields a conditional r squared of 53.23%. Such denotes that 53.23% of the variance of total space ratio per page given to an artist in a given edition can be explained by the artist’s nationality and the count through time of the number of exhibitions an artist has at the MoMA. This type of statistical analysis as far as I am aware has not been done in regards to looking at how art historical survey texts evolve. My research works to explain how the authors of <em>Janson’s History of Art</em> and <em>Gardner’s Art Through the Ages,</em> operate while choosing which artists are given any particular amount of space in their publications.</p>
</section>
<section id="research-questions" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> <strong>Research Questions:</strong></h1>
<ol type="1">
<li><p>What are the demographics (Race, Gender, Ethnicity, Nationality) of artists included in each edition of Janson’s History of Art (from 1962-2011) and Gardner’s Art Through the Ages (from 1926-2020) looking at two-dimensional works after c.&nbsp;1750?</p>
<p>Hypothesis: <em>Janson’s History of Art</em> and <em>Gardner’s Art Through the Ages</em> will include more female, nonwhite, Hispanic or Latinx artists over time; however, these artists will still be dramatically underrepresented compared to white male artists. Moreover, race and ethnicity will be more of a limiting factor than gender.</p></li>
<li><p>Which variables (gender, race, ethnicity, nationality, number of exhibitions at the MoMA or The Whitney) if any, predict the magnitude of an artist’s inclusion in art history survey texts (<em>Janson’s History of Art</em> and <em>Gardner’s Art Through the Ages</em>)?</p>
<p>Hypothesis: I hypothesize demographic information per artist will play a large role in accounting for the total variance in <code>space_ratio_per_page_total</code>. The type of race, gender, nationality, and ethnicity of an artist in theory highly impacts how much they are highlighted and discussed in introductory art history texts. Additionally, I hypothesize that if a given artist has many exhibitions in the MoMA or The Whitney, such would additionally account for variance in the outcome variable <code>space_ratio_per_page</code>. The notion behind such a hypothesis is that if an artist is being put on exhibition, they are likely to be discussed more in introductory art history texts.</p></li>
</ol>
</section>
<section id="methodology" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> <strong>Methodology:</strong></h1>
<section id="data-collection" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="data-collection"><span class="header-section-number">5.1</span> Data Collection:</h2>
<section id="textbooks" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="textbooks"><span class="header-section-number">5.1.1</span> Textbooks:</h3>
<p>Scope: I collected data from 25 different books. I cataloged 9 different books of <em>Janson’s History of Art</em>, spanning from 1963 to 2011. Additionally, I cataloged 16 different books of <em>Gardner’s Art Through the Ages,</em> spanning from 1929 to 2020. I used the particular scope of works produced after c.&nbsp;1750 that were two-dimensional. This scope allowed me to collect information more quickly to understand how the books were changing over time. Across all 25 books, there are a total of 3162 observations, which is the sum of the count of artists in every book. In the finalized, gardnerjanson_museums data set, there are 14 different variables cataloged (for further information about each variable, reference the Data Dictionary). There are a total of 414 unique artists.</p>
<p>Outcome variable:</p>
<p><code>space_ratio_per_page_total</code> = I measured with a ruler with centimeters, the length and width of text per work per artist. If the area of text was not a rectangle, I additionally collected the length and width of any extra text. I then used excel to calculate the total area of the text per work per artist. Then I additionally measured the length and width of the figure in the book of the work itself. Again, using excel, I calculated the area of the figure of the work. I then added together the area of figure of a work with the area of text written about the work, to create a variable of total space given to a work. In order to achieve a ratio between total space and the area of a page is in a respective book, as they are inconsistent, I divided the total area of a page from a respective book with the total space given to a work by an artist in a respective book.</p>
<p>Demographic variables:</p>
<p><code>artist_nationality</code> = I recorded the nationality of the artist as listed by the text. In the case the nationality of the artist was not listed, I would do a quick google search to further research their nationality. If I couldn’t find their nationality, I listed such as N/A.</p>
<p><code>artist_gender</code> = I recorded the gender of the artist as listed by the text. In the case the gender of the artist was not listed, I would do a quick google search to further research their gender. If I couldn’t find their gender, I listed such as N/A.</p>
<p><code>artist_race</code> = I recorded the race of the artist as listed by the text. I categorized race based on the guidelines of the US Census.<a href="#fn23" class="footnote-ref" id="fnref23" role="doc-noteref"><sup>23</sup></a> In the case the race of the artist was not listed, I would do a quick google search to further research their race. If I couldn’t find their race, I listed such as N/A.</p>
<p><code>artist_ethnicity</code> = I recorded the ethnicity of the artist as listed by the text. Similarly to race, I categorized ethnicity based on the guidelines of the US Census.<a href="#fn24" class="footnote-ref" id="fnref24" role="doc-noteref"><sup>24</sup></a> In the case the ethnicity of the artist was not listed, I would do a quick google search to further research their ethnicity. If I couldn’t find their ethnicity, I listed such as N/A.</p>
<p>Identifying Variables:</p>
<p><code>artist_name</code> = The name of the artist as listed by the respective book. At times, each book would spell names slightly differently, so I standardized names across editions as well as across museum exhibition data for the MoMA and The Whitney.</p>
<p><code>year</code> = I recorded the year of publication of each book.</p>
<p><code>edition_number</code> = I recorded the edition number of each book.</p>
<p><code>book</code> = I recorded which book, either Gardner or Janson, the work was mentioned.</p>
<p>Selection: As argued in the Introduction and Context, <em>Janson’s History of Art</em> and <em>Gardner’s Art Through the Ages,</em> are the two most renowned and significant art history introductory texts through roughly the last century.</p>
<p>Limitations: I have limited my data collecting in <em>Janson’s History of Art</em> and <em>Gardner’s Art Through the Ages</em> to only including two-dimensional art made after c.&nbsp;1750. This omits sculpture and architecture and how the story of art changes from the beginning of time to c.&nbsp;1750. I did such as I am most interested in how the diversity of artists changes through editions, and because it only took roughly 1/5 of the time to catalog as I was only cataloging roughly 1/5 of each book. Additionally, two-dimensional works are more frequently included in museum exhibitions spaces than works of sculpture and architecture. My research would be more robust and complete had I cataloged every work in every edition. I am fully aware of this limitation, yet I believe my conclusions are significant within my scope.</p>
</section>
<section id="museum-data" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="museum-data"><span class="header-section-number">5.1.2</span> Museum Data:</h3>
<p>Scope: My second research question is looking at if / how an artist’s inclusion in museums exhibitions impacts the amount of total area an artist is given in a particular book. I initially began this research as a group project for a class titled, “Art Markets.” In order to collect information regarding museum exhibitions, my colleague, David Smoot (’21), web scraped the MoMA’s website for the entirety of its catalog history from when its doors first opened in 1929 through the date he scraped the MoMA’s website which was March 14th, 2021. He did the same thing with The Whitney’s website and web scraped their exhibition history from 1933 through when he scraped the website, March 30th, 2021. There was a total of 10,630 observations in the MoMA data set and 13,736 at The Whitney. An observation is an appearance of an artist in an exhibition.</p>
<p>Selection: The Whitney and the MoMA were chosen as they are located in New York City, arguably the center of the art world as we know it, and because of the relative accessibility of historic exhibition data.&nbsp;</p>
<p>Limitations: The inclusion of more museums, both domestically and internationally would lend the museum data sets greater power to provide context, and an independent metric for the importance of the exhibition, such as press coverage, would be more useful as a comparison to the <code>space_ratio_per_page_total</code> in the textbook than the number of exhibitions. Also, The Whitney appears to only list their annual shows on their website prior to 1997, so only the MoMA has complete data.</p>
<p>I finished my data collection process with four separate data sets. I had one in which I collected demographic and total space information for the nine books of <em>Janson’s History of Art,</em> and a second doing the same for the sixteen books of <em>Gardner’s Art Through the Ages.</em> I then had a data set of the MoMA’s exhibition history from 1929-March 14th, 2021 and lastly a data set of The Whitney’s exhibition history from 1933-March 30th, 2021.</p>
</section>
</section>
<section id="data-preparation" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="data-preparation"><span class="header-section-number">5.2</span> Data Preparation:</h2>
<p>In order to create one data set, gardnerjanson_museums, I went through a number of steps to join data from all four in R Studio. I began with binding the rows from the Janson data set and the Gardner data set. I then created a new variable <code>artist_unique_id</code> in which I assigned a number to each artist in alphabetical order across all editions of both books. In some cases, there are artists with multiple works cataloged in a particular edition. I was able to sum the total space per work such that an artist’s name would only show up once per edition with a <code>total_space_per_page_total</code> value in centimeters squared.</p>
<p>Pivoting to joining The Whitney’s catalog history and the MoMA’s catalog history with the data set I just created with both Janson and Gardner observations, I had to create a variable called <code>whitney_count_to_year</code> and <code>moma_count_to_year</code> respectively. This is because as the publication year of books changes through time, the amount of exhibitions that are given to an artist has the possibility to change through time as well.</p>
<p><code>whitney_count_to_year</code> = The count of exhibitions held by The Whitney of a particular artist at a particular moment of time, as highlighted by <code>year</code>.</p>
<p><code>moma_count_to_year</code> = The count of exhibitions held by the Museum of Modern Art (MoMA) of a particular artist at a particular moment of time, as highlighted by <code>year</code>.</p>
</section>
<section id="model-selection" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="model-selection"><span class="header-section-number">5.3</span> Model Selection:</h2>
<section id="data-preparation-for-modeling-purposes" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="data-preparation-for-modeling-purposes"><span class="header-section-number">5.3.1</span> Data Preparation for Modeling Purposes:</h3>
<p>In order to prepare my data further for the purposes of regression, I had to re-categorize the variable of <code>artist_nationality</code> and <code>artist_race</code>. Firstly, since there are myriad nationalities recorded through all 25 books, I had to condense <code>artist_nationality</code> to <code>artist_nationality_other</code> such that I would only receive five varying betas rather than more than thirty.</p>
<p><code>artist_nationality_other</code> = The nationality of the artist. Of the total count of artists through all editions of <em>Janson’s History of Art</em> and <em>Gardner’s Art Through the Ages,</em> 77.32% account for French, Spanish, British, American and German. Therefore, the categorical strings of this variable are French, Spanish, British, American, German and Other.</p>
<p>In regard to <code>artist_race</code>, there are so few observations of artists who are non-white that when running a regression with a categorizing non-white even further into their respective cataloged races with only a handful of data points is not statistically sufficient nor informative. The buckets of information at the respective race-level were too small and therefore rank deficient. Therefore I created the variable <code>artist_race_nwi</code>.</p>
<p><code>artist_race_nwi</code> = The non-white indicator for artist race, meaning if an artist’s race is denoted as either white or non-white.</p>
<p>Lastly, I releveled my data such that the baseline demographic of artist reflects the most common category across <code>artist_race</code>, <code>artist_ethnicity</code>, <code>artist_nationality</code> and <code>artist_gender</code> respectively which is a white non-Latinx or Hispanic French man.</p>
</section>
<section id="linear-mixed-effects-model" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="linear-mixed-effects-model"><span class="header-section-number">5.3.2</span> Linear Mixed-Effects Model:</h3>
<p>We chose to use a linear mixed-effects model as the data contains a random effect at the artist level as multiple observations in the data can be by the same artist. Using a linear mixed effects model with artist name as the random effect eliminates the dependence between observations of the same artist, therefore allowing independence to be satisfied for our model. Additionally, we chose to log transform the outcome variable, the total space ratio per page is extremely right-skewed. Performing the log transformation allows for the residuals to have constant variance (homoscedasticity). In regards to choosing the combination of both main fixed effects and interaction fixed effects, we used a step-wise model selection methodology.</p>
<p>Satterthwaite test, more flexible, looking directly at p-values - non-parametric test - uses different error term, similar to a two same t-test, similar to ANOVA - analysis of variance - checking between different groups -</p>
</section>
</section>
</section>
<section id="exploratory-data-analysis-gardners-art-through-the-ages-and-jansons-history-of-art-through-editions" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Exploratory Data Analysis: <em>Gardner’s Art Through the Ages</em> and <em>Janson’s History of Art</em> Through Editions</h1>
<section id="count-through-editions" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="count-through-editions"><span class="header-section-number">6.1</span> <strong>Count Through Editions:</strong></h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/gardnercountthroughtime-1.png" class="img-fluid" alt="There are some respective lulls and peaks through time, as in the fourth edition published in 1959, there are 87 works, while in the fifth published in 1970, there is a significant regression to 69 works. Such trend is evident as well in the seventh edition published in 1980, which has 115 works, while the eighth published in 1986 regresses to 109 works. There is yet another peak at edition eleven published in 2001, with 170 works. There is then a lull over the course of two editions, ending with edition thirteen published in 2009 having 164 works." width="672"></p>
</div>
<div class="cell-output-stdout">
<pre><code># A tibble: 164 × 14
# Groups:   artist_name [164]
   artist_name            edition_number  year artist_national… artist_national…
   &lt;chr&gt;                           &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;            &lt;chr&gt;           
 1 Aaron Douglas                      13  2009 American         American        
 2 Adolphe William Bougu…             13  2009 French           French          
 3 Albert Bierstadt                   13  2009 German-American  Other           
 4 Alfred Stieglitz                   13  2009 American         American        
 5 Ana Mendieta                       13  2009 Cuban-American   Other           
 6 André Derain                       13  2009 French           French          
 7 Andy Warhol                        13  2009 American         American        
 8 Angelica Kauffmann                 13  2009 Swiss            Other           
 9 Anne Louis Girodet Tr…             13  2009 French           French          
10 Anselm Kiefer                      13  2009 German           German          
# … with 154 more rows, and 9 more variables: artist_gender &lt;chr&gt;,
#   artist_race &lt;chr&gt;, artist_ethnicity &lt;chr&gt;, book &lt;chr&gt;,
#   space_ratio_per_page_total &lt;dbl&gt;, artist_unique_id &lt;int&gt;,
#   moma_count_to_year &lt;dbl&gt;, whitney_count_to_year &lt;dbl&gt;,
#   artist_race_nwi &lt;chr&gt;</code></pre>
</div>
</div>
<p>The shape of the overall count of works by artists in <em>Gardner’s Art Through the Ages</em> is heavily left-skewed, multimodal, and asymmetrical. Such highlights how through time, more works are, on average, continually added to <em>Gardner’s Art Through the Ages</em> that are two-dimensional and made after c.&nbsp;1750. The first edition, published in 1926 by Helen Gardner, only has a a total of 21 works. Edition 15, published in 2016 as well as edition 16, published in 2020, have 182 works respectively, which is the maximum amount of works through all editions.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/jansoncountthroughtime-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-stdout">
<pre><code># A tibble: 153 × 14
# Groups:   artist_name [153]
   artist_name            edition_number  year artist_national… artist_national…
   &lt;chr&gt;                           &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;            &lt;chr&gt;           
 1 Adolphe William Bougu…              8  2011 French           French          
 2 Albert Pinkham Ryder                8  2011 American         American        
 3 Alexander Rodchenko                 8  2011 Russian          Other           
 4 Alfred Stieglitz                    8  2011 American         American        
 5 Ando Hiroshige                      8  2011 Japanese         Other           
 6 André Derain                        8  2011 French           French          
 7 Andy Warhol                         8  2011 American         American        
 8 Angelica Kauffmann                  8  2011 Swiss            Other           
 9 Anne Louis Girodet Tr…              8  2011 French           French          
10 Anselm Kiefer                       8  2011 German           German          
# … with 143 more rows, and 9 more variables: artist_gender &lt;chr&gt;,
#   artist_race &lt;chr&gt;, artist_ethnicity &lt;chr&gt;, book &lt;chr&gt;,
#   space_ratio_per_page_total &lt;dbl&gt;, artist_unique_id &lt;int&gt;,
#   moma_count_to_year &lt;dbl&gt;, whitney_count_to_year &lt;dbl&gt;,
#   artist_race_nwi &lt;chr&gt;</code></pre>
</div>
</div>
<p>The shape of the overall count of works by artists in <em>Janson’s History of Art</em> is left-skewed, unimodal and asymmetrical. Such highlights how through time, more works are added to <em>Janson’s History of Art</em> that are two-dimensional and made after c.&nbsp;1750. There is then a drop-off of works included in the seventh (published in 2007 with 163 works) and eighth (published in 2011 with 153 works) editions, when new authorship took over. Within edition five (published 1995) and edition six (published in 2001), both written by Anthony Janson, there are the same number of works, the maximum amount included in the text throughout time, 185, as compared to the count of works in the first edition, first printing, 62, and first edition, second printing, 76.</p>
</section>
<section id="gender-through-editions" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="gender-through-editions"><span class="header-section-number">6.2</span> <strong>Gender Through Editions:</strong></h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/jansongenderthroughtime-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The breakdown of artists’ gender through editions of <em>Janson’s History of Art,</em> has never dipped below 86% male, which is what the horizontal line denotes. Additionally, this visualization shows that the first two editions, (the first three books cataloged: edition 1, first printing, edition 1, second printing, and edition 2), that were written my H. W. Janson and Dora Jane Janson, contains no women. Anthony Janson, who took over authorship for the third edition in 1986, began including women. Notably, he was extremely proud of himself for diversifying his family’s art history survey text.</p>
<p>The overall percentage of male artists through all books of <em>Janson’s History of Art</em> is 89.99%.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/gardnergenderthroughtime-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The breakdown of artists’ gender through editions of <em>Gardner’s Art Through the Ages,</em> is marginally more diverse in regard to gender, as the lowest threshold of male artists is just above 81%, which is denoted by the horizontal line. Additionally, this visualization shows that the first edition in 1926 contains no female artists in our scope, but that starting in the second edition in 1936, Helen Gardner included female artists.</p>
<p>The overall percentage of male artists through all books of <em>Gardner’s Art Through the Ages</em> is 85.69%, roughly a 4.5% increase in regard to gender diversity as compared to <em>Janson’s History of Art.</em></p>
</section>
<section id="race-through-editions" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="race-through-editions"><span class="header-section-number">6.3</span> <strong>Race Through Editions:</strong></h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/jansonracethroughtime-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Pivoting to looking at race diversity in <em>Janson’s History of Art</em> through time, unsurprisingly, the three cataloged books, first two editions written by H. W. Janson and Dora Jane Janson, there were only white artists included. When their son took over authorship, he included a handful of black artists, then in the fifth edition, he added an artist by the name Kay Walkingstick, who is a Native American woman. She was included through the sixth edition then removed when the group of six professors took over. Interestingly, the black artists who are included have frequent turnover. In the seventh and eighth editions, there was an Asian artist introduced, Ando Hiroshige, a Japanese male painter who was used as a reference when discussing impressionist art.</p>
<p>The overall percentage of white artists through all editions of <em>Janson’s History of Art</em> is 97.37%.</p>
<p>ADD FIGURE OF WORK USED IN JANSON FOR ANDO HIROSHIGE</p>
<p><strong>Figure 1:</strong> Kay WalkingStick, On The Edge, 1989. Acrylic and wax and oil on canvas, 81 x 162 ½&nbsp; cm. Private collection.</p>
<p><img src="https://lh6.googleusercontent.com/-fxCinylYYA8sB2zbAHmHqqUqxQ26KdZHZgPvNBfgKfWMZqCVK_-VZk2SKqToScRwccJ1ynxTJuI_w2lp0N2BmvgfLPEWl0LO4Ll84ljfkyBkCMQwU8WH-HDC7MXBZpMstMMA8ff.png" class="img-fluid"></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/gardnerracethroughtime-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Gardner’s Art Through the Age’s</em> began with including more than just white artists, with the inclusion of Asian artists in the first edition. The most diverse a single edition has gotten thus far is just under 15% being non-white. Interestingly enough, the two editions that are least racially diverse are the seventh and eighth editions which were published in 1980 and 1986 respectively. There is a significant jump in black representation in the eleventh edition, as well as other non-white artists as the percentage of non-white artists goes from just under 4% in the tenth (1996) to close to 14% in the eleventh (2001).</p>
<p>The overall percentage of white artists through all editions of <em>Gardner’s Art Through the Ages</em> is 90.02%.</p>
</section>
<section id="ethnicity-through-editions" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="ethnicity-through-editions"><span class="header-section-number">6.4</span> <strong>Ethnicity Through Editions:</strong></h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/jansonethnicitythroughtime-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Fascinatingly, in <em>Janson’s History of Art,</em> the ratio of Hispanic or Latinx artists is the highest of all editions in the first edition, first printing. This may be because the overall count of artists was so few that having only a handful of Hispanic or Latinx artists accounted for just under 9% of the overall count of artists in the 1963 publication.</p>
<p>The overall percentage of artists who are not Hispanic or Latinx included in <em>Janson’s History of Art</em> is 95.82%.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/gardnerethnicitythroughtime-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Helen Gardner’s third edition published in 1959 was the most ethnically diverse of all 25 textbooks. This edition was published after her death, but she has passed with the intention of her book being a representation of the world’s history of art. Her efforts are evident through the percentage of Hispanic and Latinx artists, just under 22%. It is clear that her succeeding authors did not continue with such an ethnically diverse selection of artists, which has remained under 9% in every other publication.</p>
<p>The overall percentage of artists who are not Hispanic or Latinx included in <em>Janson’s History of Art</em> is 91.51%.</p>
</section>
<section id="nationality-through-editions" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="nationality-through-editions"><span class="header-section-number">6.5</span> <strong>Nationality Through Editions:</strong></h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/jansonnationalitythroughtime-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It is clear that <em>Janson’s History of Art</em> paints a western tradition through the visualization above, highlighting predominantly French, American, British, German, and Spanish artists. Through the first two editions—three books as such include the first edition revised and enlarged published in 1969—the majority nationality is French. Then, when authorship changes from Peter and Dora Janson to Anthony F. Janson in the third edition in 1986, the dominant nationality flips to American. Anthony adds American contemporary artists, such as Lee Krasner, as well as American photographers such as Dorothea Lange.</p>
<p>The most consistently represented nationality through editions, however, is French, which could be explained by the type of art highlighted from after c.&nbsp;1750: Impressionism, Post-Impressionism and Realism. Artists such as Édouard Manet and Claude Monet are French painters who enter the narrative when Peter first writes his discourse published in 1962, and who remain over time even with change in authorship due to their perpetual prominence within the art world.</p>
<p>The overall percentage of artists who are French, American, British, German or Spanish through all editions of <em>Janson’s History of Art</em> is 78.51%.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/gardnernationalitythroughtime-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The spike of the ratio of American artists included in the second edition published in 1936 could be explained by President Franklin Delano Roosevelt’s Federal Art Project during the Great Depression. The US government started funding unemployed artists in the US from 1935 through 1943.</p>
<p>This visualization also displays a gradual but significant shift in dominance from the percentage of French artists included to American artists from the 1970s through 2020.</p>
<p>The overall percentage of artists who are French, American, British, German, or Spanish through all editions of <em>Gardner’s Art Through the Ages</em> is 76.58%.</p>
</section>
</section>
<section id="exploratory-data-analysis-jansons-history-of-art-and-gardners-art-through-the-ages-vs.-total-space-ratio-per-page-per-artist-per-edition-space_ratio_per_page_total" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Exploratory Data Analysis: <em>Janson’s History of Art</em> and <em>Gardner’s Art Through the Ages vs.</em> Total Space Ratio per Page per Artist per Edition <code>space_ratio_per_page_total</code></h1>
<section id="distribution-of-space_ratio_per_page_total" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="distribution-of-space_ratio_per_page_total"><span class="header-section-number">7.1</span> Distribution of <code>space_ratio_per_page_total</code></h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/spaceratioperpagetotal-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-stdout">
<pre><code>[1] 0.4092838</code></pre>
</div>
<div class="cell-output-stdout">
<pre><code>[1] 0.2859275</code></pre>
</div>
</div>
<p>The shape of the visualization above is right-skewed, unimodal and asymmetrical. Therefore, we would want to look at the median to understand its center and interquartile range, which is the middle 50% of the range of the data to understand its spread. The median total space an artist receives is 40.93% of a page. The IQR of total space an artist receives is 28.59% of a page.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/logspaceratioperpagetotal-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In order to create less skew in our outcome variable, it is evident that log transforming total space ratio per page given to an artist in a particular edition gives the spread a much more mild right-skew than before. The shape is still unimodal and asymmetrical. I will be using the log transformation on the total space ratio per page, our outcome variable, in the linear mixed-effects model. This allows for the residuals to have constant variance.</p>
</section>
<section id="space_ratio_per_page_total-vs.-artist_gender" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="space_ratio_per_page_total-vs.-artist_gender"><span class="header-section-number">7.2</span> <code>space_ratio_per_page_total</code> vs.&nbsp;<code>artist_gender</code></h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/genderallbooks-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-stdout">
<pre><code># A tibble: 10 × 6
# Groups:   artist_name [6]
   artist_name         artist_gender edition_number  year book  space_ratio_per…
   &lt;chr&gt;               &lt;chr&gt;                  &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;
 1 Hannah Höch         Female                     8  2011 Jans…            0.940
 2 Hannah Höch         Female                    11  2001 Gard…            0.920
 3 Hannah Höch         Female                     7  2007 Jans…            0.913
 4 Élisabeth Louise V… Female                    11  2001 Gard…            0.831
 5 Cindy Sherman       Female                    11  2001 Gard…            0.830
 6 Angelica Kauffmann  Female                     8  2011 Jans…            0.797
 7 Liubov Popova       Female                     8  2011 Jans…            0.785
 8 Angelica Kauffmann  Female                    16  2020 Gard…            0.764
 9 Dorothea Rockburne  Female                    10  1996 Gard…            0.736
10 Angelica Kauffmann  Female                     7  2007 Jans…            0.733</code></pre>
</div>
<div class="cell-output-stdout">
<pre><code>[1] 0.3492886</code></pre>
</div>
<div class="cell-output-stdout">
<pre><code>[1] 0.4202227</code></pre>
</div>
<div class="cell-output-stdout">
<pre><code>[1] 0.1081594</code></pre>
</div>
</div>
<p>Interestingly enough, the median of the total ratio of space per page for female artists is 0.349, not far below the median of the total ratio of space per page in centimeters for male artists, 0.42 through all 25 varying textbooks<em>.</em> This indicates that even though the percentage of female artists as compared to male artists is 10.82%, the average amount of space allotted to a female artist is comparable to that of a male.</p>
<p>That said, there are far more male artists that are given a total ratio of space per page of over 1, meaning over a page of information regarding their work or works. No female has a total ratio of space per page of over 1. The closest female artist to having a page of area given to them is Hannah Höch. In fact, she holds the top three spots of the most area given to a woman in three separate editions: The seventh (2007) and eighth (2011) editions of <em>Janson’s History of Art</em> and the eleventh edition (2001) of <em>Gardner’s Art Through the Ages.</em></p>
<p>LOOK AT WHICH WORK OF HERS IS INCLUDED IN EACH EDITION.</p>
</section>
<section id="space_ratio_per_page_total-vs.-artist_race" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="space_ratio_per_page_total-vs.-artist_race"><span class="header-section-number">7.3</span> <code>space_ratio_per_page_total</code> vs.&nbsp;<code>artist_race</code></h2>
<div class="cell">

</div>
<p>The median of the total ratio of space given to a particular artist through all 25 books is fairly comparable across varying races. Though the count of each race is far from being comparable, the respective medians per race are as follows: American Indian or Alaska Native, .469, Asian, .344, Black or African American .375, Native Hawaiian or Other Pacific Islander, .428 and White, .413. With that being said, even though the racial diversity in regard to the ratio of count for white to non-white artists is 92.85%, once an artist is represented, the amount of area given to them is fairly similar in regard to their respectively medians.</p>
<p>Obviously, the top quartile of white artists dominates this visualization. White is the only race that has any artists given more than a page of space in any one book. Out of the top ten outliers of white artists, eight of them are Pablo Picasso, with the first five observations being from various editions of <em>Janson’s History of Art.</em></p>
</section>
<section id="space_ratio_per_page_total-vs.-artist_ethnicity" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="space_ratio_per_page_total-vs.-artist_ethnicity"><span class="header-section-number">7.4</span> <code>space_ratio_per_page_total</code> vs.&nbsp;<code>artist_ethnicity</code></h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/ethnicityallbooks-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-stdout">
<pre><code>[1] NA</code></pre>
</div>
<div class="cell-output-stdout">
<pre><code>[1] NA</code></pre>
</div>
</div>
<p>Interestingly, the median for the total space ratio per page for artists who are Hispanic or Latinx, <code>round(median(janson_HL$space_ratio_per_page_total), 3)</code> is higher than those who are Not Hispanic or Latinx, <code>round(median(janson_NHL$space_ratio_per_page_total), 3)</code>. There are <code>nrow(janson_HL)</code> observations of artists per edition who are Hispanic and Latinx and there are <code>nrow(janson_NHL)</code> observations of artists per edition who are not Hispanic or Latinx. Picasso plays a large role in such, as he is Hispanic or Latinx and is accounting for the outlyingly larger observations for <code>space_ratio_per_page_total</code>.</p>
</section>
<section id="space_ratio_per_page_total-vs.-artist_nationality_other" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="space_ratio_per_page_total-vs.-artist_nationality_other"><span class="header-section-number">7.5</span> <code>space_ratio_per_page_total</code> vs.&nbsp;<code>artist_nationality_other</code></h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/nationalityotherallbooks-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-stdout">
<pre><code># A tibble: 717 × 5
# Groups:   artist_name [132]
   artist_name      edition_number  year book    space_ratio_per_page_total
   &lt;chr&gt;                     &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                        &lt;dbl&gt;
 1 Vincent Van Gogh            7    2007 Janson                        2.16
 2 Vincent Van Gogh            2    1977 Janson                        1.79
 3 Vincent Van Gogh            3    1986 Janson                        1.63
 4 Vincent Van Gogh            1    1963 Janson                        1.55
 5 Vincent Van Gogh            1.1  1969 Janson                        1.54
 6 Vincent Van Gogh            8    2011 Janson                        1.38
 7 Vincent Van Gogh           15    2016 Gardner                       1.27
 8 Karl Bodmer                 6    1975 Gardner                       1.21
 9 Paul Klee                   6    1975 Gardner                       1.20
10 Paul Klee                   5    1970 Gardner                       1.19
# … with 707 more rows</code></pre>
</div>
<div class="cell-output-stdout">
<pre><code># A tibble: 10 × 14
# Groups:   artist_name [4]
   artist_name       edition_number  year artist_nationality artist_nationality…
   &lt;chr&gt;                      &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;              &lt;chr&gt;              
 1 Albert Bierstadt              11  2001 German-American    Other              
 2 Albert Bierstadt              12  2005 German-American    Other              
 3 Albert Bierstadt              13  2009 German-American    Other              
 4 Albert Bierstadt              14  2013 German-American    Other              
 5 Albert Bierstadt              15  2016 German-American    Other              
 6 Albert Bierstadt              16  2020 German-American    Other              
 7 Alexander Gardner             10  1996 Scottish           Other              
 8 Alfredo Guido                  3  1948 Argentine          Other              
 9 Ana Mendieta                  11  2001 Cuban-American     Other              
10 Ana Mendieta                  13  2009 Cuban-American     Other              
# … with 9 more variables: artist_gender &lt;chr&gt;, artist_race &lt;chr&gt;,
#   artist_ethnicity &lt;chr&gt;, book &lt;chr&gt;, space_ratio_per_page_total &lt;dbl&gt;,
#   artist_unique_id &lt;int&gt;, moma_count_to_year &lt;dbl&gt;,
#   whitney_count_to_year &lt;dbl&gt;, artist_race_nwi &lt;chr&gt;</code></pre>
</div>
</div>
<table class="table">
<colgroup>
<col style="width: 19%">
<col style="width: 43%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Artist Nationality</th>
<th>Percent of Total Count Through all 25 books</th>
<th>Median Total Ratio of Space per Page</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>American</td>
<td>28.72%</td>
<td>.377</td>
</tr>
<tr class="even">
<td>British</td>
<td>10.03%</td>
<td>.372</td>
</tr>
<tr class="odd">
<td>French</td>
<td>27.51%</td>
<td>.535</td>
</tr>
<tr class="even">
<td>German</td>
<td>8.10%</td>
<td>.375</td>
</tr>
<tr class="odd">
<td>Other</td>
<td>22.68%</td>
<td>.380</td>
</tr>
<tr class="even">
<td>Spanish</td>
<td>2.97%</td>
<td>.889</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="results" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Results</h1>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/sjplot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-stdout">
<pre><code>                                                 GVIF Df GVIF^(1/(2*Df))
artist_nationality_other                     1.822957  5        1.061885
moma_count_to_year                           6.610187  1        2.571028
artist_nationality_other:moma_count_to_year 10.843105  5        1.269157</code></pre>
</div>
</div>
<p>GET PVALUES FOR COEFFICIENTS - STATISTICALLY SIGNIFICANT - GO THROUGH INTERPRETATIONS WITH LOG TRANSFORMATION AND MIXED EFFECTS MODEL - CONFIRM MODEL DIAGNOSTICS - AIC / BIC FOR MIXED EFFECTS -</p>
<div class="cell">
<div class="cell-output-stdout">
<pre><code>           R2m      R2c
[1,] 0.1565302 0.568739</code></pre>
</div>
</div>
<p>Marginal R2 provides the variance explained only by fixed effects and conditional R2 provides the variance explained by the entire model, i.e., both fixed effects and random effects.</p>
<p>Model Diagnostics : Check for linearity, independence, residuals, normal distribution of the residuals - no pattern in residuals, constant variance</p>
<p>RESOURCE: https://www.ssc.wisc.edu/sscc/pubs/MM/MM_DiagInfer.html</p>
<p>Plotting : log transform some variables : Fitted v. Residuals</p>
</section>
<section id="discussion" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Discussion</h1>
</section>
<section id="limitations-and-next-steps" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Limitations and Next Steps</h1>
<p><strong>Relevance of Research and Connection to Bigger Picture</strong></p>
<p>Statistical analysis in tandem to art historical research leads to a more comprehensive and thorough report when looking at the communication between art history and other players in the art world. The decisions and publications of art historians and experts are in communication with art sales, museum exhibitions and collections. The intersectionality of the realm of art, as well as the significance of data in the aggregate mustn’t go ignored. Such research additionally allows for the lack of diversity in regards to gender and more severely race to be highlighted objectively and effectively. The role of art historical narratives has decreased significantly, but discrimination in terms of representation for minority artists is still an issue at the forefront of not only art history programs, but additionally in museum spaces. How can the art world further create space for diversity looking forward? In terms of museums, many institutions have been making efforts to not only diversify their collections and exhibitions through deaccessioning, but also diversifying their staff through opening up positions specifically for individuals of minority demographics. It will be interesting to see how, if at all, art historical surveys will adapt going forward, or if they will be left in the past.&nbsp;</p>
<p><strong>Suggestions for Further Research</strong></p>
<p>There are myriad next steps for such research going forward. Firstly, it would be ideal to extend the museum datato exhibitions and acquisitions from museums of various sizes and locations in order to garner a more representative sample of the art museum sector beyond major institutions in New York City. Secondly, we would love to use more complex statistics in order to predict the likelihood of an artist’s inclusion in an art historical survey. Therefore, creating a statistical model using variables such as inclusion in museum spaces, prices fetched at auction, and number of publications by art experts on a particular artist in order to predict inclusion would greatly add to our research. Lastly, other art historical narratives should also be catalogued. This would allow for us to not only look at the changes per edition of the Janson’s History of Art, but also how various art historical canons differ from one another, leaving which artists out and which artists in. I would collect data through editions of Marilyn Stokstad et al.’s Art History, the other two art historical narratives that are most utilized in introductory courses across the United States.</p>
</section>
<section id="appendix" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Appendix</h1>
<section id="assumptions" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="assumptions"><span class="header-section-number">11.1</span> Assumptions</h2>
<section id="residuals-and-constant-variance" class="level3" data-number="11.1.1">
<h3 data-number="11.1.1" class="anchored" data-anchor-id="residuals-and-constant-variance"><span class="header-section-number">11.1.1</span> Residuals and Constant Variance</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/diagnostics-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The very low values of the predicted values have very low variability for residuals but for the bulk of the data, there is constant variability in the residuals.</p>
</section>
<section id="normality" class="level3" data-number="11.1.2">
<h3 data-number="11.1.2" class="anchored" data-anchor-id="normality"><span class="header-section-number">11.1.2</span> Normality</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/density-histogram-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The distribution of the residuals is approximately normal.</p>
</section>
<section id="linearity" class="level3" data-number="11.1.3">
<h3 data-number="11.1.3" class="anchored" data-anchor-id="linearity"><span class="header-section-number">11.1.3</span> Linearity</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Chapter1_files/figure-html/linearitymoma-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There is no pattern left behind therefore linearity is satisfied. There is a linear relationship between the response and predictor variables. (not sure if this is correct)</p>
</section>
<section id="independence" class="level3" data-number="11.1.4">
<h3 data-number="11.1.4" class="anchored" data-anchor-id="independence"><span class="header-section-number">11.1.4</span> Independence</h3>
<p>Since we are using a mixed-effects model, and our random effect is per artist, we eliminate the dependence of our observations had we not used a mixed effects model. Between artists, we expect the observations to be independent.</p>
</section>
</section>
<section id="data-dictionary" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="data-dictionary"><span class="header-section-number">11.2</span> Data Dictionary</h2>
<p>Outcome:</p>
<p><code>space_ratio_per_page_total</code> = The area in centimeters squared of both the text and the figure of a particular artist in a given edition of <em>Janson’s History of Art</em> divided by the area in centimeters squared of a single page of the respective edition.</p>
<p>Potential Predictors:</p>
<p><code>artist_gender</code> = The gender of the artist.</p>
<p><code>artist_race</code> = The race of the artist.</p>
<p><code>artist_race_nwi</code> = The non-white indicator for artist race, meaning if an artist’s race is denoted as either white or non-white.</p>
<p><code>artist_ethnicity</code> = The ethnicity of the artist.</p>
<p><code>artist_nationality_other</code> = The nationality of the artist. Of the total count of artists through all editions of <em>Gardner’s Art Through the Ages</em> and <em>Janson’s History of Art</em>, 77.32% account for French, Spanish, British, American and German. Therefore, the categorical strings of this variable are French, Spanish, British, American, German and Other.</p>
<p><code>whitney_count_to_year</code> = The count of exhibitions held by The Whitney of a particular artist at a particular moment of time, as highlighted by <code>year</code>.</p>
<p><code>moma_count_to_year</code> = The count of exhibitions held by the Museum of Modern Art (MoMA) of a particular artist at a particular moment of time, as highlighted by <code>year</code>.</p>
<p><code>year</code> = The year of publication for a given edition of Janson or Gardner.</p>
<p>Other variables:</p>
<p><code>edition_number</code> = The edition number of the textbook from either Janson’s History of Art or Gardner’s Art Through the Ages.</p>
<p><code>book</code> = Which book, either Janson or Gardner the particular artist at that particular time was included.</p>
<p><code>artist_unique_id</code> = A unique identifying number assigned to artists across books and editions denoted in alphabetical order.</p>
</section>
</section>
<section id="bibliography" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> Bibliography</h1>
<p>“100 Best-Selling Art History Books of All Time.” Book Authority.<br>
https://bookauthority.org/books/best-selling-art-history-books.&nbsp;&nbsp;</p>
<p>Bolin, Paul E. “Discussions and Depictions of Women in H. W. Janson’s History of Art, Fourth<br>
Edition.” Journal of Social Theory in Art Education. Vol. 15. 1996: 146-159.<br>
https://core.ac.uk/download/pdf/51288476.pdf.</p>
<p>Davies, Penelope J.E., Walter B. Denny, Frima Fox Hofrichter, Joseph F. Jacobs, Ann S. Roberts,<br>
David L. Simon. Janson’s History of Art. Seventh Edition. New Jersey: Pearson Prentice<br>
Hall, 2007.</p>
<p>Davies, Penelope J.E., Walter B. Denny, Frima Fox Hofrichter, Joseph F. Jacobs, Ann S. Roberts,<br>
David L. Simon.&nbsp; Janson’s History of Art. Eighth Edition. New Jersey: Pearson<br>
Prentice Hall, 2011.</p>
<p>Hills, Patricia. “Art History Textbooks: The Hidden Persuaders.” Artforum. Summer 1976.<br>
https://www.artforum.com/print/197606/art-history-textbooks-the-hidden-<br>
persuaders-69128.&nbsp;</p>
<p>Ingalls, Zoë. “A Son Revises His Father’s Classic Art-History Textbook.” The Chronicle of<br>
Higher Education. August 11, 1995. https://www.chronicle.com/article/a-son-<br>
revises-his-fathers-classic-art-history-textbook/.</p>
<p>Janson, Anthony. University of North Carolina Wilmington Archives and Special Collections.<br>
By Sherman Hayes. March 15-19, 2007.&nbsp;</p>
<p>Janson, H. W., and Anthony F. Janson. History of Art. 3rd Edition. New York: Harry N.<br>
Abrams, 1986.<br>
Janson, H. W., and Anthony F. Janson. History of Art. 4th Edition. New York: Harry N.<br>
Abrams, 1991.</p>
<p>Janson, H. W., and Anthony F. Janson. History of Art. 5th Edition. New York: Harry N.<br>
Abrams. New Jersey: Prentice Hall, 1995.&nbsp;</p>
<p>Janson, H. W., and Anthony F. Janson. History of Art. 6th Edition. Harry N. Abrams.<br>
New York: Prentice Hall, 2001.</p>
<p>Janson, H. W., and Dora Jane Janson. History of Art: A Survey of the Major Visual Arts<br>
from the Dawn of History to the Present Day. First Edition, Second Printing. New York:<br>
Harry N. Abrams, 1963.&nbsp;</p>
<p>Janson, H. W., and Dora Jane Janson. History of Art: A Survey of the Major<br>
Visual Arts from the Dawn of History to the Present Day. First Edition Revised and<br>
Enlarged. New Jersey: Prentice Hall, 1969.</p>
<p>Janson, H. W., and Dora Jane Janson. History of Art: A Survey of the Major Visual Arts<br>
from the Dawn of History to the Present Day. Second Edition. New York: Harry N.<br>
Abrams, 1977.&nbsp;</p>
<p>Kennedy, Randy. “Revising Art History’s Big Book: Who’s In and Who Comes Out?” New York<br>
Times. March 7, 2006. https://www.nytimes.com/2006/03/07/arts/design/<br>
revising-art-historys-big-book-whos-in-and-who-comes-out.html.</p>
<p>Peers, Alexandra. “Canon Fodder.” ARTnews.com. February 1, 2006.<br>
https://www.artnews.com/art-news/news/canon-fodder-135/.&nbsp;</p>
<p>Russell, John. “Prof.&nbsp;H. W. Janson is Dead at 68; Wrote Best-Selling ‘History of Art.’” The New<br>
York Times. October 3, 1982. https://www.nytimes.com/1982/10/03/nyregion/prof-h-w-<br>
Janson-is-dead-at-68-wrote-best-selling-history-of-art.html.</p>
<p>Sears, Elizabeth and Charlotte Schoell-Glass. “An Émigré Art Historian and American: H. W.<br>
Janson.” The Art Bulletin, Vol. 95, No.&nbsp;2. June 2013: 219-242. https://www-jstor-<br>
org.proxy.lib.duke.edu/stable/pdf/43188810.Pdf?ab_ segments=0%252Fbasic<br>
_search_gsv2%252Fcontrol&amp;refreqid= excelsior%3A650026c2e9a3cd0873008880<br>
2a88e215.</p>
<p>Weidman, Jeffrey. “Many Are Culled but Few Are Chosen: Janson’s History of Art, Its<br>
Reception, Emulators, Legacy, and Current Demise.” Journal of Scholarly Publishing<br>
Vol. 38. No.&nbsp;2. January 2007: 85-107. https://muse.jhu.edu/article/209994/pdf.</p>


</section>
<section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2>Footnotes</h2>

<ol>
<li id="fn1" role="doc-endnote"><p>https://arthistorians.info/crosbys<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p>Alexandra Peers, “Canon Fodder,” Artnews.com, (February 1, 2006), https://www.artnews.com/art-news/news/canon-fodder-135/.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3" role="doc-endnote"><p>H. W. Janson and Dora Jane Janson, (1963),&nbsp; History of Art: A Survey of the Major Visual Arts from the Dawn of History to the Present Day, First Edition, Second Printing, New York: Harry N. Abrams: 17.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4" role="doc-endnote"><p>Market Research Report on Introductory Art History, dated March 15, 1972, prepared for McGraw-Hill College Textbook Division and Follow-up Report, dated Spring, 1973. Citation from Patricia Hills, “Art History Textbooks: The Hidden Persuaders,” Artforum, (Summer 1976), https://www.artforum.com/print/197606/art-history-textbooks-the-hidden-persuaders-69128.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5" role="doc-endnote"><p>John Russell, “Prof H. W Janson is Dead at 68; Wrote Best-Selling ‘History of Art,’” The New York Times, (October 3, 1982), https://www.nytimes.com/1982/10/03/nyregion/prof-h-w-Janson-is-dead-at-68 -wrote-best-selling-history-of-art.html.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6" role="doc-endnote"><p>John Russell, “Prof H. W Janson is Dead at 68; Wrote Best-Selling ‘History of Art,’” The New York Times, (October 3, 1982), https://www.nytimes.com/1982/10/03/nyregion/prof-h-w-Janson-is-dead-at-68 -wrote-best-selling-history-of-art.html.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7" role="doc-endnote"><p>Zoë Ingalls, “A Son Revises His Father’s Classic Art-History Textbook,” The Chronicle of Higher Education, (August 11, 1995), https://www.chronicle.com/article/a-son-revises-his-fathers-classic- art-history-textbook/.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8" role="doc-endnote"><p>Zoë Ingalls, “A Son Revises His Father’s Classic Art-History Textbook,” The Chronicle of Higher Education, (August 11, 1995), https://www.chronicle.com/article/a-son-revises-his-fathers-classic- art-history-textbook/.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9" role="doc-endnote"><p>Zoë Ingalls, “A Son Revises His Father’s Classic Art-History Textbook,” The Chronicle of Higher Education, (August 11, 1995), https://www.chronicle.com/article/a-son-revises-his-fathers-classic- art-history-textbook/.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10" role="doc-endnote"><p>Alexandra Peers, “Canon Fodder.”<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11" role="doc-endnote"><p>Jeffrey Weidman, “Many Are Culled but Few Are Chosen: Janson’s History of Art, Its Reception, Emulators, Legacy, and Current Demise.” Journal of Scholarly Publishing 38, no. 2 (January 2007): 96. https://muse.jhu.edu/article/209994/pdf.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12" role="doc-endnote"><p>“100 Best-Selling Art HIstory Books of All Time,” Book Authority, https://bookauthority.org/books/best-selling-art-history-books.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13" role="doc-endnote"><p>There are discrepancies through the first and sixth editions of only Harry N. Abrams being listed as the publisher on the book itself and Harry N. Abrams and Prentice-Hall both being listed. Harry N. Abrams was the primary publisher through the first sixth editions as Prentice-Hall was their distributor.<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14" role="doc-endnote"><p>I cataloged the first edition, second printing, published in 1963, but the first edition, first printing was published in 1962. There is no different between printings.<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15" role="doc-endnote"><p>Dora Jane Janson is only listed upon opening the book to the title page. She is not listed anywhere on the exterior of the Janson’s History of Art across the first edition, second printing, first edition (revised and enlarged) fourteenth printing, nor the second edition.<a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16" role="doc-endnote"><p>Anthony Janson, interview by Sherman Hayes, University of North Carolina Wilmington Archives and Special Collections, (March 15-19, 2007): 11.<a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn17" role="doc-endnote"><p>Anthony Janson, interview by Sherman Hayes, University of North Carolina Wilmington Archives and Special Collections, (March 15-19, 2007): 7.<a href="#fnref17" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn18" role="doc-endnote"><p>Anthony Janson, interview by Sherman Hayes, University of North Carolina Wilmington Archives and Special Collections, (March 15-19, 2007): 9.<a href="#fnref18" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn19" role="doc-endnote"><p>Jeffrey Weidman, “Many are Culled but Few Are Chosen,” 94.<a href="#fnref19" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn20" role="doc-endnote"><p>Jeffrey Weidman, “Many Are Culled but Few Are Chosen: Janson’s History of Art, Its Reception, Emulators, Legacy, and Current Demise.” Journal of Scholarly Publishing 38, no. 2 (January 2007): 85-107. https://muse.jhu.edu/article/209994/pdf.<a href="#fnref20" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn21" role="doc-endnote"><p>Randy Kennedy, “Revising Art History’s Big Book: Who’s In and Who Comes Out?” New York Times, (March 7, 2006), https://www.nytimes.com/2006/03/07/arts/design/revising-art-historys-big-book- whos-in-and-who-comes-out.html.<a href="#fnref21" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn22" role="doc-endnote"><p>Paul E. Bolin, “Discussions and Depictions of Women in H. W. Janson’s History of Art, Fourth Edition,” Journal of Social Theory in Art Education, Vol. 15.(1996), pp.&nbsp;146-159. https://core.ac.uk/download/pdf/51288476.pdf.<a href="#fnref22" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn23" role="doc-endnote"><p>https://www.census.gov/topics/population/race/about.html.</p>
<p>https://www.mobap.edu/wp-content/uploads/2013/01/US-Census-Bureau-Definitions-of-Race-and-Ethnicity.pdf#:~:text=Definition%3A%20The%20U.S.%20Census%20Bureau%20adheres%20to%20the,Hispanics%20and%20Latinos%20may%20be%20of%20any%20race.<a href="#fnref23" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn24" role="doc-endnote"><p>https://www.mobap.edu/wp-content/uploads/2013/01/US-Census-Bureau-Definitions-of-Race-and-Ethnicity.pdf#:~:text=Definition%3A%20The%20U.S.%20Census%20Bureau%20adheres%20to%20the,Hispanics%20and%20Latinos%20may%20be%20of%20any%20race.<a href="#fnref24" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>
</main> <!-- /main -->
<script type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    setTimeout(function() {
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Preface</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../Chapter2/Chapter2.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Model Exploration</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->


</body></html>