{
  "hash": "489628c8d92390c2651941e73f8cafc9",
  "result": {
    "markdown": "# Results\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n## Descriptive Analysis: Research Question 1\n\nWhat are the demographics (artist race, gender, ethnicity, nationality) of artists included in each edition of Janson's History of Art (from 1962-2011) and Gardner's Art Through the Ages (from 1926-2020) looking at two-dimensional works after c.\n1750?\n\n### Count Through Editions\n\nIn @fig-gardnercountthroughtime, we can see ... **TO DO: FIX**.\n\n::: {.cell}\n::: {.cell-output-display}\n![sOME CAPTION GOES HERE, SHORTER THAN ALT TEXT USUALLY.](03-results_files/figure-pdf/fig-gardnercountthroughtime-1.pdf){#fig-gardnercountthroughtime fig-alt='There are some respective lulls and peaks through time, as in the fourth edition published in 1959, there are 87 works, while in the fifth published in 1970, there is a significant regression to 69 works. Such trend is evident as well in the seventh edition published in 1980, which has 115 works, while the eighth published in 1986 regresses to 109 works. There is yet another peak at edition eleven published in 2001, with 170 works. There is then a lull over the course of two editions, ending with edition thirteen published in 2009 having 164 works.'}\n:::\n:::\n\nThe shape of the overall count of works by artists in *Gardner's Art Through the Ages* is heavily left-skewed, multimodal, and asymmetrical.\nSuch highlights how through time, more works are, on average, continually added to *Gardner's Art Through the Ages* that are two-dimensional and made after c.\n1750.\nThe first edition, published in 1926 by Helen Gardner, only has a total of 21 works.\nEdition 15, published in 2016 as well as edition 16, published in 2020, have 182 works respectively, which is the maximum amount of works through all editions.\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-results_files/figure-pdf/jansoncountthroughtime-1.pdf)\n:::\n:::\n\nThe shape of the overall count of works by artists in *Janson's History of Art* is left-skewed, unimodal and asymmetrical.\nSuch highlights how through time, more works are added to *Janson's History of Art* that are two-dimensional and made after c.\n1750.\nThere is then a drop-off of works included in the seventh (published in 2007 with 163 works) and eighth (published in 2011 with 153 works) editions, when new authorship took over.\nWithin edition five (published 1995) and edition six (published in 2001), both written by Anthony Janson, there are the same number of works, the maximum amount included in the text throughout time, 185, as compared to the count of works in the first edition, first printing, 62, and first edition, second printing, 76.\n\n### Gender Through Editions\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-results_files/figure-pdf/jansongenderthroughtime-1.pdf)\n:::\n:::\n\nThe breakdown of artists' gender through editions of *Janson's History of Art,* has never dipped below 86% male, which is what the horizontal line denotes.\nAdditionally, this visualization shows that the first two editions, (the first three books cataloged: edition 1, first printing, edition 1, second printing, and edition 2), that were written my H.\nW. Janson and Dora Jane Janson, contains no women.\nAnthony Janson, who took over authorship for the third edition in 1986, began including discourse surrounding female artists.\nNotably, he was extremely proud of himself for diversifying his family's art history survey text.[^results-35]\n\n[^results-35]: anthony janson interview\n\nThe overall percentage of male artists through all books of *Janson's History of Art* is 89.99%.\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-results_files/figure-pdf/gardnergenderthroughtime-1.pdf)\n:::\n:::\n\nThe breakdown of artists' gender through editions of *Gardner's Art Through the Ages,* is marginally more diverse in regard to gender, as the lowest threshold of male artists is just above 81%, which is denoted by the horizontal line.\nAdditionally, this visualization shows that the first edition in 1926 contains no female artists in our scope, but that starting in the second edition in 1936, Helen Gardner began including female artists.\n*Gardner's History of Art* included female artists in the scope of two-dimensional works after c.\n1750 50 years earlier than *Janson's History of Art.*\n\nThe overall percentage of male artists through all books of *Gardner's Art Through the Ages* is 85.69%, roughly a 4.5% increase in regard to gender diversity as compared to *Janson's History of Art.*\n\n### Race Through Editions\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-results_files/figure-pdf/jansonracethroughtime-1.pdf)\n:::\n:::\n\nPivoting to looking at race diversity in *Janson's History of Art* through time, unsurprisingly, the three cataloged books, first two editions written by H.\nW. Janson and Dora Jane Janson, there were only white artists included.\nWhen their son took over authorship, he included a handful of black artists, then in the fifth edition, he added an artist by the name of Kay Walkingstick (1935-present), who is a Native American woman.\nShe was included through the sixth edition then removed when the group of six professors took over.\n\nAnthony Janson states in the fifth edition that Walkingstick combines \"Neo-Expressionism and Neo-Abstraction in a particularly fruitful way...\"[^results-36] The work below was brought forth after the death of her husband in 1989, as she outpours her grief onto the canvas.\nThe left panel, as Janson writes, is \"built up in thick coats of paint applied mainly by her hands,\" with a fan shape in the center which suggests a manmade feature in a primitive landscape and also acts as a sign, investing the canvas mysterious emblematic significance.\nThe right half was painted in an Expressionist style and releases anger through the various layers of color.\nWalkingstick's diptych display aspects of nature as a spiritual center, of calm contemplation, powerful emotion, and order in chaos.\n[^results-37]\n\n[^results-36]: Janson edition 5, 834\n\n[^results-37]: Janson fifther edition, 835\n\n![](images/on-the-edge.png){width=\"600\"}\n\nFigure \\_\\_ : Kay WalkingStick, *On The Edge*, 1989.\nAcrylic and wax and oil on canvas, 81 x 162 ½  cm.\nPrivate collection.\n\nInterestingly, the black artists who are included have frequent turnover.\nThe only black artist that enters *Janson's History of Art* in the third edition (1986) and remains through the latest edition (2011) is painter Henry Ossawa Tanner (1859-1937).\nNotably, in the fifth edition by Anthony Janson, he begins his discourse on Tanner with,\n\nThanks in large part to \\[Thomas\\] Eakins' enlightened attitude, Philadelphia became the leading center of minority artists in the United States.\nEakins encouraged women and blacks to study art seriously at a time when professional careers were closed to them.\nAfrican-Americans has no chance to enter the arts before Emancipation, and after the Civil War the situation improved only gradually.\n[^results-38]\n\n[^results-38]: Janson's fifth edition, 724.\n\nJanson is seemingly distracted by Tanner's race and how Thomas Eakins provided space for him rather than beginning discourse directly about the aesthetics and significance of Tanner's work itself.\nHe only mentions Tanner's name in the following sentence, allotting only half of the area of text to the history of the artist and the work itself.\n\nIn the fifth edition of Janson's History of Art, Anthony Janson chose to include *The Banjo Lesson,* which he painted after he moved permenantly to Paris, which \"bears Eakins' unmistakable influence.\"[^results-39] Tanner, who is described as the \"first important black painter\" is given space in the text, yet is not properly and independently discussed.\n\n[^results-39]: Janson fifth edition, 724.\n\n![](images/the-banjo-lesson.png){width=\"263\"}\n\nFigure \\_\\_ : Henry Ossawa Tanner, *The Banjo Lesson,* c.\n1893.\nOil on canvas, 121.9 x 88.9 cm.\nHampton University Museum, Hampton, Virginia.\n\nIn the seventh and eighth editions, there was an Asian artist introduced, Ando Hiroshige, a Japanese male painter who was used as a reference when discussing Edgar Degas.\nIn Janson's eighth edition, the group of six authors highlights the use of flatness in Hiroshige's composition.\nThe flatness he employs is used to discuss how the \"spatial contraction of Japanese prints certainly influence Degas and Manet...\"[^results-40] Similarly to the example of Tanner, Hiroshige stands as another example of a minority artist included to be compared to the work of a white male artist.\n\n[^results-40]: Janson Edition 8, 871.\n\n![](images/plum-estate.png){width=\"261\"}\n\nFigure \\_\\_: Ando Hiroshige, *Plum Estate, Kamiedo,* from the series *One Hundred Famous Views of Edo.* 1857.\nWoodblock print, 34 x 22.6 cm.\nBrooklyn Museum of Art, New York.\n\nThe overall percentage of white artists through all editions of *Janson's History of Art* is 97.37%.\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-results_files/figure-pdf/gardnerracethroughtime-1.pdf)\n:::\n:::\n\n::: {.cell}\n\n:::\n\nIn @tbl-gardner-asian, we can see Asian artists with high space ratio... **TO DO: FIX.**\n\n::: {#tbl-gardner-asian .cell tbl-cap='Asian artists whose names are known with highest space ratio per page across editions of Gardner.'}\n::: {.cell-output-display}\n|Artist             | Edition| Space ratio per page|\n|:------------------|-------:|--------------------:|\n|Suzuki Harunobu    |      16|                0.874|\n|Ando Hiroshige     |      15|                0.853|\n|Suzuki Harunobu    |      11|                0.852|\n|Suzuki Harunobu    |      14|                0.847|\n|Katsushika Hokusai |      13|                0.687|\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-stdout}\n```\n# A tibble: 55 x 14\n   artist_name      edition_number  year artist_nationality artist_nationality_~\n   <chr>                     <dbl> <dbl> <chr>              <chr>               \n 1 Aaron Douglas                 9  1991 American           American            \n 2 Aaron Douglas                10  1996 American           American            \n 3 Aaron Douglas                11  2001 American           American            \n 4 Aaron Douglas                12  2005 American           American            \n 5 Aaron Douglas                13  2009 American           American            \n 6 Aaron Douglas                14  2013 American           American            \n 7 Aaron Douglas                15  2016 American           American            \n 8 Aaron Douglas                16  2020 American           American            \n 9 Carrie Mae Weems             15  2016 American           American            \n10 Carrie Mae Weems             16  2020 American           American            \n# ... with 45 more rows, and 9 more variables: artist_gender <chr>,\n#   artist_race <chr>, artist_ethnicity <chr>, book <chr>,\n#   space_ratio_per_page_total <dbl>, artist_unique_id <dbl>,\n#   moma_count_to_year <dbl>, whitney_count_to_year <dbl>,\n#   artist_race_nwi <chr>\n```\n:::\n:::\n\n*Gardner's Art Through the Age's* began with including more than just white artists, with the inclusion of Asian artists in the first edition.\nThe most diverse a single edition has gotten thus far is just under 15% being non-white.\nInterestingly enough, the two editions that are least racially diverse are the seventh and eighth editions which were published in 1980 and 1986 respectively.\nThere is a significant jump in black representation in the eleventh edition, as well as other non-white artists as the percentage of non-white artists goes from just under 4% in the tenth (1996) to close to 14% in the eleventh (2001).\n\nThe first named Asian artist was Suzuki Harunobu in the third edition in 1959.\nHe remains within *Gardner's History of Art* through the latest 16th edition (2020).\n\n![](images/glow-andon.png){width=\"320\"}\n\nFigure \\_\\_: Suzuki Harunobu.\n*The Evening Glow of the Ando (Night Lantern).* 1765.\\\nColor woodblock print, 28.6 × 21.5 cm.\nArt Institute of Chicago, Chicago.\n\nThe first black artists were added in the ninth edition (1991).\nThe only two black artists to be included in all editions from then on are Aaron Douglas and Henry Ossawa Tanner.\n\nFigure \\_\\_: Aaron Douglas\n\nThe overall percentage of white artists through all editions of *Gardner's Art Through the Ages* is 90.02%.\n\n### Ethnicity Through Editions\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-results_files/figure-pdf/jansonethnicitythroughtime-1.pdf)\n:::\n:::\n\nFascinatingly, in *Janson's History of Art,* the ratio of Hispanic or Latinx artists is the highest of all editions in the first edition, first printing.\nThis may be because the overall count of artists was so few that having only a handful of Hispanic or Latinx artists accounted for just under 9% of the overall count of artists in the 1963 publication.\n\nThe overall percentage of artists who are not Hispanic or Latinx included in *Janson's History of Art* is 95.82%.\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-results_files/figure-pdf/gardnerethnicitythroughtime-1.pdf)\n:::\n:::\n\nHelen Gardner's third edition published in 1959 was the most ethnically diverse of all 25 textbooks.\nThis edition was published after her death, but she has passed with the intention of her book being a representation of the world's history of art.\nHer efforts are evident through the percentage of Hispanic and Latinx artists, just under 22%.\nIt is clear that her succeeding authors did not continue with such an ethnically diverse selection of artists, which has remained under 9% in every other publication.\n\nThe overall percentage of artists who are not Hispanic or Latinx included in *Janson's History of Art* is 91.51%.\n\n### Nationality Through Editions\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-results_files/figure-pdf/jansonnationalitythroughtime-1.pdf)\n:::\n:::\n\nIt is clear that *Janson's History of Art* paints a western tradition through the visualization above, highlighting predominantly French, American, British, German, and Spanish artists.\nThrough the first two editions---three books as such include the first edition revised and enlarged published in 1969---the majority nationality is French.\nThen, when authorship changes from Peter and Dora Janson to Anthony F. Janson in the third edition in 1986, the dominant nationality flips to American.\nAnthony adds American contemporary artists, such as Jackson Pollock and Lee Krasner, as well as American photographers such as Dorothea Lange.\n\nThe most consistently represented nationality through editions, however, is French, which could be explained by the type of art highlighted from after c.\n1750: Impressionism, Post-Impressionism and Realism.\nArtists such as Édouard Manet and Claude Monet are French painters who enter the narrative when Peter first writes his discourse published in 1962, and who remain over time even with change in authorship due to their perpetual prominence within the art world.\n\nThe overall percentage of artists who are French, American, British, German or Spanish through all editions of *Janson's History of Art* is 78.51%.\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-results_files/figure-pdf/gardnernationalitythroughtime-1.pdf)\n:::\n:::\n\nThe spike of the ratio of American artists included in the second edition published in 1936 could be explained by President Franklin Delano Roosevelt's Federal Art Project during the Great Depression.\nThe US government started funding unemployed artists in the US from 1935 through 1943.\n\nThis visualization also displays a gradual but significant shift in dominance from the percentage of French artists included to American artists from the 1970s through 2020.\n\nThe overall percentage of artists who are French, American, British, German, or Spanish through all editions of *Gardner's Art Through the Ages* is 76.58%.\n\n## Exploratory Data Analysis: Research Question 2\n\nWhich variables (artist gender, race, ethnicity, nationality, number of exhibitions at the MoMA or The Whitney) if any, predict the magnitude of an artist's inclusion in art history survey texts (*Janson's History of Art* and *Gardner's Art Through the Ages*).\n\n### Distribution of Total Space Ratio Per Page\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-results_files/figure-pdf/spaceratioperpagetotal-1.pdf)\n:::\n:::\n\nThe shape of the visualization above is right-skewed, unimodal and asymmetrical.\nTherefore, we would want to look at the median to understand its center and interquartile range, which is the middle 50% of the range of the data to understand its spread.\nThe median total space an artist receives is 40.93% of a page.\nThe IQR of total space an artist receives is 28.59% of a page.\n\n### Total Space Ratio Per Page vs. Artist Gender\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-results_files/figure-pdf/genderallbooks-1.pdf)\n:::\n\n::: {.cell-output-stdout}\n```\n# A tibble: 10 x 6\n   artist_name         artist_gender edition_number  year book  space_ratio_per~\n   <chr>               <chr>                  <dbl> <dbl> <chr>            <dbl>\n 1 Hannah Höch         Female                     8  2011 Jans~            0.940\n 2 Hannah Höch         Female                    11  2001 Gard~            0.920\n 3 Hannah Höch         Female                     7  2007 Jans~            0.913\n 4 Élisabeth Louise V~ Female                    11  2001 Gard~            0.831\n 5 Cindy Sherman       Female                    11  2001 Gard~            0.830\n 6 Angelica Kauffmann  Female                     8  2011 Jans~            0.797\n 7 Liubov Popova       Female                     8  2011 Jans~            0.785\n 8 Angelica Kauffmann  Female                    16  2020 Gard~            0.764\n 9 Dorothea Rockburne  Female                    10  1996 Gard~            0.736\n10 Angelica Kauffmann  Female                     7  2007 Jans~            0.733\n```\n:::\n\n::: {.cell-output-stdout}\n```\n[1] 0.3492886\n```\n:::\n\n::: {.cell-output-stdout}\n```\n[1] 0.4202227\n```\n:::\n\n::: {.cell-output-stdout}\n```\n[1] 0.1081594\n```\n:::\n:::\n\nInterestingly enough, the median of the total ratio of space per page for female artists is 0.349, not far below the median of the total ratio of space per page in centimeters for male artists, 0.42 through all 25 varying textbooks*.* This indicates that even though the percentage of female artists as compared to male artists is 10.82%, the average amount of space allotted to a female artist is comparable to that of a male.\n\nThat said, there are far more male artists that are given a total ratio of space per page of over 1, meaning over a page of information regarding their work or works.\nNo female has a total ratio of space per page of over 1.\nThe closest female artist to having a page of area given to them is Hannah Höch.\nIn fact, she holds the top three spots of the most area given to a woman in three separate editions: The seventh (2007) and eighth (2011) editions of *Janson's History of Art* and the eleventh edition (2001) of *Gardner's Art Through the Ages.* Her work included, *Cut with the Kitchen Knife Dada through the Last Weimar Beer Belly Cultural Epoch of Germany,* stands as an example of photomontage introducing the illogical and chaotic Dadaism.\n\n```{=html}\n<!--\n![](images/the-kitchen-knife.png){width=\"299\"}\n-->\n```\nFigure \\_\\_ : Hannah Höch.\n*Cut with the Kitchen Knife Dada through the Last Weimar Beer Belly Cultural Epoch of Germany.* 1919-1920.\nPhotomontage, 114.3 x 90.17 cm.\nNeue Nationalgalerie, Staatliche Museen, Berlin.\n\n### Total Space Ratio Per Page vs. Artist Race\n\n::: {.cell}\n\n:::\n\nThe median of the total ratio of space given to a particular artist through all 25 books is fairly comparable across varying races.\nThough the count of each race is far from being comparable, the respective medians per race are as follows: American Indian or Alaska Native, .469, Asian, .344, Black or African American .375, Native Hawaiian or Other Pacific Islander, .428 and White, .413.\nWith that being said, even though the racial diversity in regard to the ratio of count for white to non-white artists is 92.85%, once an artist is represented, the amount of area given to them is fairly similar in regard to their respectively medians.\n\nObviously, the top quartile of white artists dominates this visualization.\nWhite is the only race that has any artists given more than a page of space in any one book.\nOut of the top ten outliers of white artists, eight of them are Pablo Picasso, with the first five observations being from various editions of *Janson's History of Art.*\n\n### Total Space Ratio Per Page vs. Artist Ethnicity\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-results_files/figure-pdf/ethnicityallbooks-1.pdf)\n:::\n\n::: {.cell-output-stdout}\n```\n[1] NA\n```\n:::\n\n::: {.cell-output-stdout}\n```\n[1] NA\n```\n:::\n:::\n\nInterestingly, the median for the total space ratio per page for artists who are Hispanic or Latinx, `round(median(janson_HL$space_ratio_per_page_total), 3)` is higher than those who are Not Hispanic or Latinx, `round(median(janson_NHL$space_ratio_per_page_total), 3)`.\nThere are `nrow(janson_HL)` observations of artists per edition who are Hispanic and Latinx and there are `nrow(janson_NHL)` observations of artists per edition who are not Hispanic or Latinx.\nPicasso plays a large role in such, as he is Hispanic or Latinx and is accounting for the outlyingly larger observations for `space_ratio_per_page_total`.\n\n### Total Space Ratio Per Page vs. Artist Nationality\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-results_files/figure-pdf/nationalityotherallbooks-1.pdf)\n:::\n\n::: {.cell-output-stdout}\n```\n# A tibble: 10 x 5\n   artist_name      edition_number  year book    space_ratio_per_page_total\n   <chr>                     <dbl> <dbl> <chr>                        <dbl>\n 1 Vincent Van Gogh            7    2007 Janson                        2.16\n 2 Vincent Van Gogh            2    1977 Janson                        1.79\n 3 Vincent Van Gogh            3    1986 Janson                        1.63\n 4 Vincent Van Gogh            1    1963 Janson                        1.55\n 5 Vincent Van Gogh            1.1  1969 Janson                        1.54\n 6 Vincent Van Gogh            8    2011 Janson                        1.38\n 7 Vincent Van Gogh           15    2016 Gardner                       1.27\n 8 Karl Bodmer                 6    1975 Gardner                       1.21\n 9 Paul Klee                   6    1975 Gardner                       1.20\n10 Paul Klee                   5    1970 Gardner                       1.19\n```\n:::\n:::\n\n+--------------------+---------------------------------------------+--------------------------------------+\n| Artist Nationality | Percent of Total Count Through all 25 books | Median Total Ratio of Space per Page |\n+====================+=============================================+======================================+\n| American           | 28.72%                                      | .377                                 |\n+--------------------+---------------------------------------------+--------------------------------------+\n| British            | 10.03%                                      | .372                                 |\n+--------------------+---------------------------------------------+--------------------------------------+\n| French             | 27.51%                                      | .535                                 |\n+--------------------+---------------------------------------------+--------------------------------------+\n| German             | 8.10%                                       | .375                                 |\n+--------------------+---------------------------------------------+--------------------------------------+\n| Other              | 22.68%                                      | .380                                 |\n+--------------------+---------------------------------------------+--------------------------------------+\n| Spanish            | 2.97%                                       | .889                                 |\n+--------------------+---------------------------------------------+--------------------------------------+\n\n## Model Output: Research Question 2\n\nWhich variables (artist gender, race, ethnicity, nationality, number of exhibitions at the MoMA or The Whitney) if any, predict the magnitude of an artist's inclusion in art history survey texts (*Janson's History of Art* and *Gardner's Art Through the Ages*)?\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-results_files/figure-pdf/sjplot-1.pdf)\n:::\n:::\n\n$$\n\\begin{aligned}\n\\widehat{Total Space RatioPerPage} = -0.988 &+ 0.233\\times French \\\\\n&-0.058\\times Other \\\\\n&-0.015\\times British \\\\\n&-0.078\\times German \\\\\n&+ .571\\times Spanish \\\\\n&-.011\\times MoMA \\\\\n&+ .023\\times French \\times MoMACountToYear\\\\\n&+ .015 \\times Other \\times MoMACountToYear\\\\\n&+ .014 \\times British \\times MoMACountToYear\\\\\n&+ .022 \\times German \\times MoMACountToYear\\\\\n&+ .032 \\times Spanish \\times MoMACountToYear\\\\\n\\end{aligned}\n$$\n\nAfter step-wise model evaluation, the model that is most parsimonious with the highest conditional r squared is a model using only artist nationality and the count to year of the number of exhibitions an artist is included in at the MoMA and the interaction between the two.\n\n::: {.cell}\n::: {.cell-output-stdout}\n```\n           R2m      R2c\n[1,] 0.1565302 0.568739\n```\n:::\n:::\n\nWith a log transformation applied to the outcome variable as it is heavily right-skewed, my linear mixed-effects model yields a conditional r squared of 53.23%.\nSuch denotes that 53.23% of the variance of total space ratio per page given to an artist in a given edition can be explained by the model.",
    "supporting": [
      "03-results_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}